// This -*- C++ -*- file has been generated by the Python package
// NinjaNumGen, which is distributed with the Ninja library.

#include "6photons_num.hh"

#include <ninja/num_defs.hh>
#include <ninja/ninjanumgen.hh>

#define NINJA_NUM SixPhotons
#define NINJA_RANK_MINUS_N (0)
#define NINJA_NUM_NAMESPACE 0

#if NINJA_NUM_NAMESPACE
namespace NINJA_NUM_NAMESPACE {
#endif

  ninja::Complex NINJA_NUM::evaluate(const ninja::ComplexMomentum & ninjaQ,
                                     const ninja::Complex & ninjaMu2,
                                     int ninja_cut,
                                     const ninja::PartitionInt ninja_cutidx[])
  {
    ninja::Complex ninja_result;
ninja::ComplexMomentum L1 = ninjaQ+k1;
ninja::ComplexMomentum L2 = ninjaQ+p2;
ninja::ComplexMomentum L3 = ninjaQ+p3;
ninja::ComplexMomentum L4 = ninjaQ+p4;
ninja::ComplexMomentum L5 = ninjaQ-k6;
ninja::ComplexMomentum L6 = ninjaQ;
    (void)(ninjaQ);
    (void)(ninjaMu2);
    (void)(ninja_cut);
    (void)(ninja_cutidx);
NinjaAbbrType ninjanumabbr[14];  (void)(ninjanumabbr);
  
 ninjanumabbr[-1+1]= ninjaMP ( L1 , eps12 ) ; 
  ninjanumabbr[-1+2]= ninjaMP ( L2 , eps23 ) ; 
  ninjanumabbr[-1+3]= ninjaMP ( L3 , eps34 ) ; 
  ninjanumabbr[-1+4]= ninjaMP ( L4 , eps45 ) ; 
  ninjanumabbr[-1+5]= ninjaMP ( L5 , eps56 ) ; 
  ninjanumabbr[-1+6]= ninjaMP ( L6 , eps61 ) ; 
  ninjanumabbr[-1+7]= ninjaMP ( L1 , eps21 ) ; 
  ninjanumabbr[-1+8]= ninjaMP ( L2 , eps32 ) ; 
  ninjanumabbr[-1+9]= ninjaMP ( L3 , eps43 ) ; 
  ninjanumabbr[-1+10]= ninjaMP ( L4 , eps54 ) ; 
  ninjanumabbr[-1+11]= ninjaMP ( L5 , eps65 ) ; 
  ninjanumabbr[-1+12]= ninjaMP ( L6 , eps16 ) ; 
  ninjanumabbr[-1+13]= - ninjanumabbr[-1+7]* ninjanumabbr[-1+8]* ninjanumabbr[-1+11]
 * ninjanumabbr[-1+12]* ninjanumabbr[-1+10]* ninjanumabbr[-1+9]; 
  ninjanumabbr[-1+14]= - ninjanumabbr[-1+3]* ninjanumabbr[-1+2]* ninjanumabbr[-1+4]* 
 ninjanumabbr[-1+5]* ninjanumabbr[-1+6]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+13]= ninjanumabbr[-1+13]+ ninjanumabbr[-1+14]; 
  
 ninja_result = 
 NINJA_REAL(64)* ninjanumabbr[-1+13]; 
      return ninja_result;
  }

  void NINJA_NUM::muExpansion(const ninja::ComplexMomentum ninjaV[],
                              const ninja::PartitionInt ninja_cutidx[],
                              ninja::Complex ninjaC[])
  {
  const int ninjaidxt0 = 0;
    ninja::ComplexMomentum ninjaA0 = ninjaV[0];
#if (NINJA_RANK_MINUS_N > 0)
    ninja::ComplexMomentum ninjaA1 = ninjaV[1];
    (void)(ninjaA1);
#endif
    (void)(ninjaA0);
    (void)(ninja_cutidx);
    (void)(ninjaC);
NinjaAbbrType ninjanumabbr[14];  (void)(ninjanumabbr);
  
 ninjanumabbr[-1+1]= ninjaMP ( ninjaA0 , eps12 ) ; 
  ninjanumabbr[-1+2]= ninjaMP ( ninjaA0 , eps23 ) ; 
  ninjanumabbr[-1+3]= ninjaMP ( ninjaA0 , eps34 ) ; 
  ninjanumabbr[-1+4]= ninjaMP ( ninjaA0 , eps45 ) ; 
  ninjanumabbr[-1+5]= ninjaMP ( ninjaA0 , eps56 ) ; 
  ninjanumabbr[-1+6]= ninjaMP ( ninjaA0 , eps61 ) ; 
  ninjanumabbr[-1+7]= ninjaMP ( ninjaA0 , eps21 ) ; 
  ninjanumabbr[-1+8]= ninjaMP ( ninjaA0 , eps32 ) ; 
  ninjanumabbr[-1+9]= ninjaMP ( ninjaA0 , eps43 ) ; 
  ninjanumabbr[-1+10]= ninjaMP ( ninjaA0 , eps54 ) ; 
  ninjanumabbr[-1+11]= ninjaMP ( ninjaA0 , eps65 ) ; 
  ninjanumabbr[-1+12]= ninjaMP ( ninjaA0 , eps16 ) ; 
  ninjanumabbr[-1+13]= - ninjanumabbr[-1+7]* ninjanumabbr[-1+8]* ninjanumabbr[-1+11]
 * ninjanumabbr[-1+12]* ninjanumabbr[-1+10]* ninjanumabbr[-1+9]; 
  ninjanumabbr[-1+14]= - ninjanumabbr[-1+3]* ninjanumabbr[-1+2]* ninjanumabbr[-1+4]* 
 ninjanumabbr[-1+5]* ninjanumabbr[-1+6]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+13]= ninjanumabbr[-1+13]+ ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+13]= NINJA_REAL(64)* ninjanumabbr[-1+13]; 
  
 ninjaC[0+ninjaidxt0]= 
 ninjanumabbr[-1+13]; 
    }

  void NINJA_NUM::t3Expansion(const ninja::ComplexMomentum & ninjaA,
                              const ninja::ComplexMomentum & ninjaE3,
                              const ninja::ComplexMomentum & ninjaE4,
                              const ninja::Complex & ninjaP,
                              int ninja_mindeg, int ninja_cut,
                              const ninja::PartitionInt ninja_cutidx[],
                              ninja::Complex ninjaC[])
  {
  const int ninjaidxt3mu0 = 0;
  const int ninjaidxt2mu0 = 1;
  const int ninjaidxt1mu0 = 2;
  const int ninjaidxt1mu2 = 3;
  const int ninjaidxt0mu0 = 4;
  const int ninjaidxt0mu2 = 5;
ninja::ComplexMomentum ninjaAl1 = ninjaA+k1;
ninja::ComplexMomentum ninjaAl2 = ninjaA+p2;
ninja::ComplexMomentum ninjaAl3 = ninjaA+p3;
ninja::ComplexMomentum ninjaAl4 = ninjaA+p4;
ninja::ComplexMomentum ninjaAl5 = ninjaA-k6;
ninja::ComplexMomentum ninjaAl6 = ninjaA;
    (void)(ninjaA);
    (void)(ninjaE3);
    (void)(ninjaE4);
    (void)(ninjaP);
    (void)(ninja_mindeg);
    (void)(ninja_cut);
    (void)(ninja_cutidx);
    (void)(ninjaC);
    {
NinjaAbbrType ninjanumabbr[30];  (void)(ninjanumabbr);
  
 ninjanumabbr[-1+1]= ninjaMP ( ninjaE3 , eps12 ) ; 
  ninjanumabbr[-1+2]= ninjaMP ( ninjaE3 , eps23 ) ; 
  ninjanumabbr[-1+3]= ninjaMP ( ninjaE3 , eps34 ) ; 
  ninjanumabbr[-1+4]= ninjaMP ( ninjaE3 , eps45 ) ; 
  ninjanumabbr[-1+5]= ninjaMP ( ninjaE3 , eps56 ) ; 
  ninjanumabbr[-1+6]= ninjaMP ( eps61 , ninjaAl6 ) ; 
  ninjanumabbr[-1+7]= ninjaMP ( ninjaE3 , eps61 ) ; 
  ninjanumabbr[-1+8]= ninjaMP ( eps56 , ninjaAl5 ) ; 
  ninjanumabbr[-1+9]= ninjaMP ( eps45 , ninjaAl4 ) ; 
  ninjanumabbr[-1+10]= ninjaMP ( eps34 , ninjaAl3 ) ; 
  ninjanumabbr[-1+11]= ninjaMP ( eps23 , ninjaAl2 ) ; 
  ninjanumabbr[-1+12]= ninjaMP ( eps12 , ninjaAl1 ) ; 
  ninjanumabbr[-1+13]= ninjaMP ( ninjaE3 , eps21 ) ; 
  ninjanumabbr[-1+14]= ninjaMP ( ninjaE3 , eps32 ) ; 
  ninjanumabbr[-1+15]= ninjaMP ( ninjaE3 , eps43 ) ; 
  ninjanumabbr[-1+16]= ninjaMP ( ninjaE3 , eps54 ) ; 
  ninjanumabbr[-1+17]= ninjaMP ( ninjaE3 , eps65 ) ; 
  ninjanumabbr[-1+18]= ninjaMP ( eps16 , ninjaAl6 ) ; 
  ninjanumabbr[-1+19]= ninjaMP ( ninjaE3 , eps16 ) ; 
  ninjanumabbr[-1+20]= ninjaMP ( eps65 , ninjaAl5 ) ; 
  ninjanumabbr[-1+21]= ninjaMP ( eps54 , ninjaAl4 ) ; 
  ninjanumabbr[-1+22]= ninjaMP ( eps43 , ninjaAl3 ) ; 
  ninjanumabbr[-1+23]= ninjaMP ( eps32 , ninjaAl2 ) ; 
  ninjanumabbr[-1+24]= ninjaMP ( eps21 , ninjaAl1 ) ; 
  ninjanumabbr[-1+25]= - ninjanumabbr[-1+20]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+26]= - ninjanumabbr[-1+18]* ninjanumabbr[-1+17]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+26]+ ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+15]* ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+26]= ninjanumabbr[-1+19]* ninjanumabbr[-1+17]; 
  ninjanumabbr[-1+27]= - ninjanumabbr[-1+22]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+27]+ ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+16]* ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+26]= ninjanumabbr[-1+26]* ninjanumabbr[-1+15]; 
  ninjanumabbr[-1+27]= - ninjanumabbr[-1+21]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+27]+ ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+13]* ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+26]= ninjanumabbr[-1+16]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+27]= - ninjanumabbr[-1+24]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+27]+ ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+14]* ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+27]= - ninjanumabbr[-1+11]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+28]= - ninjanumabbr[-1+12]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+27]+ ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+7]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+28]= ninjanumabbr[-1+1]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+29]= - ninjanumabbr[-1+6]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+29]+ ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+3]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+28]= ninjanumabbr[-1+28]* ninjanumabbr[-1+7]; 
  ninjanumabbr[-1+29]= - ninjanumabbr[-1+10]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+29]+ ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+4]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+28]= ninjanumabbr[-1+28]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+29]= - ninjanumabbr[-1+9]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+29]+ ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+27]= ninjanumabbr[-1+5]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+26]= ninjanumabbr[-1+26]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+29]= - ninjanumabbr[-1+23]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+28]= ninjanumabbr[-1+4]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+30]= - ninjanumabbr[-1+8]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+25]= ninjanumabbr[-1+30]+ ninjanumabbr[-1+29]+ 
 ninjanumabbr[-1+27]+ ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+25]= NINJA_REAL(64)* ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+27]= - ninjanumabbr[-1+5]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+26]= - ninjanumabbr[-1+14]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+26]= ninjanumabbr[-1+27]+ ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+26]= NINJA_REAL(64)* ninjanumabbr[-1+26]; 
  
 ninjaC[0+ninjaidxt3mu0]= 
 ninjanumabbr[-1+26]; 
  
 ninjaC[0+ninjaidxt2mu0]= 
 ninjanumabbr[-1+25]; 
      }
    if (ninja_mindeg > 1+NINJA_RANK_MINUS_N) {
NinjaAbbrType ninjanumabbr[73];  (void)(ninjanumabbr);
  
 ninjanumabbr[-1+1]= ninjaMP ( ninjaE3 , eps12 ) ; 
  ninjanumabbr[-1+2]= ninjaMP ( ninjaE3 , eps23 ) ; 
  ninjanumabbr[-1+3]= ninjaMP ( ninjaE3 , eps34 ) ; 
  ninjanumabbr[-1+4]= ninjaMP ( ninjaE3 , eps45 ) ; 
  ninjanumabbr[-1+5]= ninjaMP ( ninjaE3 , eps56 ) ; 
  ninjanumabbr[-1+6]= ninjaMP ( ninjaE4 , eps61 ) ; 
  ninjanumabbr[-1+7]= ninjaMP ( ninjaE3 , eps61 ) ; 
  ninjanumabbr[-1+8]= ninjaMP ( ninjaE4 , eps56 ) ; 
  ninjanumabbr[-1+9]= ninjaMP ( eps56 , ninjaAl5 ) ; 
  ninjanumabbr[-1+10]= ninjaMP ( eps61 , ninjaAl6 ) ; 
  ninjanumabbr[-1+11]= ninjaMP ( ninjaE4 , eps45 ) ; 
  ninjanumabbr[-1+12]= ninjaMP ( eps45 , ninjaAl4 ) ; 
  ninjanumabbr[-1+13]= ninjaMP ( ninjaE4 , eps34 ) ; 
  ninjanumabbr[-1+14]= ninjaMP ( eps34 , ninjaAl3 ) ; 
  ninjanumabbr[-1+15]= ninjaMP ( ninjaE4 , eps23 ) ; 
  ninjanumabbr[-1+16]= ninjaMP ( eps23 , ninjaAl2 ) ; 
  ninjanumabbr[-1+17]= ninjaMP ( ninjaE4 , eps12 ) ; 
  ninjanumabbr[-1+18]= ninjaMP ( eps12 , ninjaAl1 ) ; 
  ninjanumabbr[-1+19]= ninjaMP ( ninjaE3 , eps21 ) ; 
  ninjanumabbr[-1+20]= ninjaMP ( ninjaE3 , eps32 ) ; 
  ninjanumabbr[-1+21]= ninjaMP ( ninjaE3 , eps43 ) ; 
  ninjanumabbr[-1+22]= ninjaMP ( ninjaE3 , eps54 ) ; 
  ninjanumabbr[-1+23]= ninjaMP ( ninjaE3 , eps65 ) ; 
  ninjanumabbr[-1+24]= ninjaMP ( ninjaE4 , eps16 ) ; 
  ninjanumabbr[-1+25]= ninjaMP ( ninjaE3 , eps16 ) ; 
  ninjanumabbr[-1+26]= ninjaMP ( ninjaE4 , eps65 ) ; 
  ninjanumabbr[-1+27]= ninjaMP ( eps65 , ninjaAl5 ) ; 
  ninjanumabbr[-1+28]= ninjaMP ( eps16 , ninjaAl6 ) ; 
  ninjanumabbr[-1+29]= ninjaMP ( ninjaE4 , eps54 ) ; 
  ninjanumabbr[-1+30]= ninjaMP ( eps54 , ninjaAl4 ) ; 
  ninjanumabbr[-1+31]= ninjaMP ( ninjaE4 , eps43 ) ; 
  ninjanumabbr[-1+32]= ninjaMP ( eps43 , ninjaAl3 ) ; 
  ninjanumabbr[-1+33]= ninjaMP ( ninjaE4 , eps32 ) ; 
  ninjanumabbr[-1+34]= ninjaMP ( eps32 , ninjaAl2 ) ; 
  ninjanumabbr[-1+35]= ninjaMP ( ninjaE4 , eps21 ) ; 
  ninjanumabbr[-1+36]= ninjaMP ( eps21 , ninjaAl1 ) ; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+21]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+37]* ninjanumabbr[-1+30]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+22]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+40]= ninjanumabbr[-1+39]* ninjanumabbr[-1+32]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+38]+ ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+40]= ninjanumabbr[-1+21]* ninjanumabbr[-1+22]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+40]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+41]+ ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+42]= ninjanumabbr[-1+41]* ninjanumabbr[-1+20]; 
  ninjanumabbr[-1+43]= ninjanumabbr[-1+40]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+43]* ninjanumabbr[-1+34]; 
  ninjanumabbr[-1+42]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+42]= ninjanumabbr[-1+42]* ninjanumabbr[-1+36]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+38]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+40]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+46]= ninjanumabbr[-1+45]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+46]; 
  ninjanumabbr[-1+46]= ninjanumabbr[-1+44]* ninjanumabbr[-1+34]; 
  ninjanumabbr[-1+47]= ninjanumabbr[-1+22]* ninjanumabbr[-1+32]; 
  ninjanumabbr[-1+48]= ninjanumabbr[-1+30]* ninjanumabbr[-1+21]; 
  ninjanumabbr[-1+47]= ninjanumabbr[-1+47]+ ninjanumabbr[-1+48]; 
  ninjanumabbr[-1+48]= ninjanumabbr[-1+47]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+48]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+50]= ninjanumabbr[-1+30]* ninjanumabbr[-1+32]; 
  ninjanumabbr[-1+51]= ninjanumabbr[-1+50]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+23]* ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+52]+ ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+49]* ninjanumabbr[-1+20]; 
  ninjanumabbr[-1+42]= ninjanumabbr[-1+42]+ ninjanumabbr[-1+46]+ 
 ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+46]= - ninjanumabbr[-1+25]* ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+16]* ninjanumabbr[-1+5]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+2]* ninjanumabbr[-1+9]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+52]+ ninjanumabbr[-1+53]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+52]* ninjanumabbr[-1+4]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+2]* ninjanumabbr[-1+5]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+54]* ninjanumabbr[-1+12]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]+ ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+53]* ninjanumabbr[-1+18]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+52]* ninjanumabbr[-1+12]; 
  ninjanumabbr[-1+57]= ninjanumabbr[-1+56]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+55]+ ninjanumabbr[-1+57]; 
  ninjanumabbr[-1+57]= ninjanumabbr[-1+16]* ninjanumabbr[-1+9]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+4]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+57]* ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+59]+ ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+59]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+60]= ninjanumabbr[-1+58]* ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+61]= ninjanumabbr[-1+52]* ninjanumabbr[-1+60]; 
  ninjanumabbr[-1+62]= ninjanumabbr[-1+54]* ninjanumabbr[-1+4]; 
  ninjanumabbr[-1+63]= ninjanumabbr[-1+62]* ninjanumabbr[-1+18]; 
  ninjanumabbr[-1+64]= ninjanumabbr[-1+54]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+64]* ninjanumabbr[-1+12]; 
  ninjanumabbr[-1+63]= ninjanumabbr[-1+63]+ ninjanumabbr[-1+65]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+63]* ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+59]+ ninjanumabbr[-1+61]+ 
 ninjanumabbr[-1+65]; 
  ninjanumabbr[-1+61]= - ninjanumabbr[-1+7]* ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+62]= ninjanumabbr[-1+62]* ninjanumabbr[-1+17]; 
  ninjanumabbr[-1+64]= ninjanumabbr[-1+64]* ninjanumabbr[-1+11]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+58]* ninjanumabbr[-1+8]; 
  ninjanumabbr[-1+66]= ninjanumabbr[-1+65]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+62]= ninjanumabbr[-1+62]+ ninjanumabbr[-1+64]+ 
 ninjanumabbr[-1+66]; 
  ninjanumabbr[-1+64]= ninjanumabbr[-1+15]* ninjanumabbr[-1+5]; 
  ninjanumabbr[-1+66]= ninjanumabbr[-1+64]* ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+66]= ninjanumabbr[-1+66]+ ninjanumabbr[-1+62]; 
  ninjanumabbr[-1+66]= ninjanumabbr[-1+66]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+58]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+68]= ninjanumabbr[-1+67]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+66]= ninjanumabbr[-1+66]+ ninjanumabbr[-1+68]; 
  ninjanumabbr[-1+68]= ninjanumabbr[-1+66]* ninjanumabbr[-1+7]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]* ninjanumabbr[-1+29]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+39]* ninjanumabbr[-1+31]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]+ ninjanumabbr[-1+39]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+37]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+69]= ninjanumabbr[-1+45]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+70]= ninjanumabbr[-1+43]* ninjanumabbr[-1+35]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+39]+ ninjanumabbr[-1+69]+ 
 ninjanumabbr[-1+70]; 
  ninjanumabbr[-1+69]= ninjanumabbr[-1+39]* ninjanumabbr[-1+20]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+45]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+70]= ninjanumabbr[-1+45]* ninjanumabbr[-1+33]; 
  ninjanumabbr[-1+69]= ninjanumabbr[-1+69]+ ninjanumabbr[-1+70]; 
  ninjanumabbr[-1+70]= ninjanumabbr[-1+69]* ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+71]= ninjanumabbr[-1+67]* ninjanumabbr[-1+6]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+71]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+73]= ninjanumabbr[-1+20]* ninjanumabbr[-1+45]* ninjanumabbr[-1+24]; 
  ninjanumabbr[-1+68]= ninjanumabbr[-1+70]+ ninjanumabbr[-1+73]+ 
 ninjanumabbr[-1+72]+ ninjanumabbr[-1+68]; 
  ninjanumabbr[-1+70]= - ninjaP * ninjanumabbr[-1+68]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+52]* ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+63]= ninjanumabbr[-1+63]+ ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+72]= - ninjanumabbr[-1+3]* ninjanumabbr[-1+63]; 
  ninjanumabbr[-1+67]= - ninjanumabbr[-1+14]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+67]+ ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+10]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+43]* ninjanumabbr[-1+36]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+72]+ ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+20]* ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+45]* ninjanumabbr[-1+34]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+45]+ ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+72]= - ninjanumabbr[-1+28]* ninjanumabbr[-1+45]; 
  ninjanumabbr[-1+46]= ninjanumabbr[-1+70]+ ninjanumabbr[-1+61]+ 
 ninjanumabbr[-1+72]+ ninjanumabbr[-1+46]+ ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+46]= NINJA_REAL(64)* ninjanumabbr[-1+46]; 
  ninjanumabbr[-1+61]= ninjanumabbr[-1+12]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+18]* ninjanumabbr[-1+4]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+61]+ ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+5]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+58]* ninjanumabbr[-1+9]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+58]+ ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+58]* ninjanumabbr[-1+15]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]* ninjanumabbr[-1+11]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+8]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+70]= ninjanumabbr[-1+4]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]+ ninjanumabbr[-1+70]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]* ninjanumabbr[-1+18]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+1]* ninjanumabbr[-1+52]* ninjanumabbr[-1+11]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+61]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]* ninjanumabbr[-1+17]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+65]* ninjanumabbr[-1+16]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+67]+ ninjanumabbr[-1+58]+ 
 ninjanumabbr[-1+54]+ ninjanumabbr[-1+52]+ ninjanumabbr[-1+65]+ 
 ninjanumabbr[-1+53]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+52]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+62]* ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+63]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+64]* ninjanumabbr[-1+60]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+52]+ ninjanumabbr[-1+53]+ 
 ninjanumabbr[-1+58]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+52]* ninjanumabbr[-1+7]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+22]* ninjanumabbr[-1+31]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+29]* ninjanumabbr[-1+21]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+40]* ninjanumabbr[-1+35]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+29]* ninjanumabbr[-1+32]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+30]* ninjanumabbr[-1+31]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]+ ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]* ninjanumabbr[-1+19]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+48]= ninjanumabbr[-1+48]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+38]* ninjanumabbr[-1+35]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+53]+ ninjanumabbr[-1+54]+ 
 ninjanumabbr[-1+48]+ ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+38]* ninjanumabbr[-1+20]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+39]* ninjanumabbr[-1+34]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+33]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+40]= ninjanumabbr[-1+40]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+40]+ ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]* ninjanumabbr[-1+20]; 
  ninjanumabbr[-1+40]= ninjanumabbr[-1+43]* ninjanumabbr[-1+33]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]+ ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]* ninjanumabbr[-1+36]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+38]+ ninjanumabbr[-1+37]+ 
 ninjanumabbr[-1+39]+ ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]* ninjanumabbr[-1+25]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+3]* ninjanumabbr[-1+6]* ninjanumabbr[-1+63]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+66]* ninjanumabbr[-1+10]; 
  ninjanumabbr[-1+40]= ninjanumabbr[-1+69]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+43]= ninjanumabbr[-1+71]* ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+45]* ninjanumabbr[-1+24]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+38]+ ninjanumabbr[-1+43]+ 
 ninjanumabbr[-1+39]+ ninjanumabbr[-1+44]+ ninjanumabbr[-1+40]+ 
 ninjanumabbr[-1+37]+ ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+38]= - NINJA_REAL(64)* ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+39]= - NINJA_REAL(64)* ninjanumabbr[-1+68]; 
  ninjanumabbr[-1+37]= - ninjaP * ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+40]= - ninjanumabbr[-1+10]* ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+28]* ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+43]= - ninjanumabbr[-1+14]* ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+44]= - ninjanumabbr[-1+57]* ninjanumabbr[-1+61]; 
  ninjanumabbr[-1+45]= - ninjanumabbr[-1+4]* ninjanumabbr[-1+57]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+45]- ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+18]* ninjanumabbr[-1+45]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+45]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+3]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+45]= - ninjanumabbr[-1+60]* ninjanumabbr[-1+57]; 
  ninjanumabbr[-1+43]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+45]+ 
 ninjanumabbr[-1+43]; 
  ninjanumabbr[-1+43]= ninjanumabbr[-1+7]* ninjanumabbr[-1+43]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+47]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+50]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+44]= - ninjanumabbr[-1+45]- ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+20]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+41]= - ninjanumabbr[-1+34]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+36]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+44]= - ninjanumabbr[-1+34]* ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+45]= - ninjanumabbr[-1+20]* ninjanumabbr[-1+27]* 
 ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+41]+ ninjanumabbr[-1+45]+ 
 ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+25]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]+ ninjanumabbr[-1+43]+ 
 ninjanumabbr[-1+42]+ ninjanumabbr[-1+41]+ ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+37]= NINJA_REAL(64)* ninjanumabbr[-1+37]; 
  
 ninjaC[0+ninjaidxt1mu0]= 
 ninjanumabbr[-1+46]; 
  
 ninjaC[0+ninjaidxt1mu2]= 
 ninjanumabbr[-1+39]; 
  
 ninjaC[0+ninjaidxt0mu0]= 
 ninjanumabbr[-1+37]; 
  
 ninjaC[0+ninjaidxt0mu2]= 
 ninjanumabbr[-1+38]; 
      }
  }

  void NINJA_NUM::t2Expansion(const ninja::ComplexMomentum & ninjaA0,
                              const ninja::ComplexMomentum & ninjaA1,
                              const ninja::ComplexMomentum & ninjaE3,
                              const ninja::ComplexMomentum & ninjaE4,
                              const ninja::Complex ninjaP[],
                              int ninja_mindeg, int ninja_cut,
                              const ninja::PartitionInt ninja_cutidx[],
                              ninja::Complex ninjaC[])
  {
  const int ninjaidxt2x0mu0 = 0;
  const int ninjaidxt1x0mu0 = 1;
  const int ninjaidxt1x1mu0 = 2;
  const int ninjaidxt0x0mu0 = 3;
  const int ninjaidxt0x0mu2 = 4;
  const int ninjaidxt0x1mu0 = 5;
  const int ninjaidxt0x2mu0 = 6;
ninja::ComplexMomentum ninjaA0l1 = ninjaA0+k1;
ninja::ComplexMomentum ninjaA0l2 = ninjaA0+p2;
ninja::ComplexMomentum ninjaA0l3 = ninjaA0+p3;
ninja::ComplexMomentum ninjaA0l4 = ninjaA0+p4;
ninja::ComplexMomentum ninjaA0l5 = ninjaA0-k6;
ninja::ComplexMomentum ninjaA0l6 = ninjaA0;
    const ninja::Complex ninjaP0 = ninjaP[0];
    const ninja::Complex ninjaP1 = ninjaP[1];
    const ninja::Complex ninjaP2 = ninjaP[2];
    (void)(ninjaA0);
    (void)(ninjaA1);
    (void)(ninjaE3);
    (void)(ninjaE4);
    (void)(ninjaP0);
    (void)(ninjaP1);
    (void)(ninjaP2);
    (void)(ninja_mindeg);
    (void)(ninja_cut);
    (void)(ninja_cutidx);
    (void)(ninjaC);
    {
NinjaAbbrType ninjanumabbr[49];  (void)(ninjanumabbr);
  
 ninjanumabbr[-1+1]= ninjaMP ( ninjaE3 , eps12 ) ; 
  ninjanumabbr[-1+2]= ninjaMP ( ninjaE3 , eps23 ) ; 
  ninjanumabbr[-1+3]= ninjaMP ( ninjaE3 , eps34 ) ; 
  ninjanumabbr[-1+4]= ninjaMP ( ninjaE3 , eps45 ) ; 
  ninjanumabbr[-1+5]= ninjaMP ( ninjaE3 , eps56 ) ; 
  ninjanumabbr[-1+6]= ninjaMP ( eps61 , ninjaA0l6 ) ; 
  ninjanumabbr[-1+7]= ninjaMP ( ninjaE3 , eps61 ) ; 
  ninjanumabbr[-1+8]= ninjaMP ( eps56 , ninjaA0l5 ) ; 
  ninjanumabbr[-1+9]= ninjaMP ( eps45 , ninjaA0l4 ) ; 
  ninjanumabbr[-1+10]= ninjaMP ( eps34 , ninjaA0l3 ) ; 
  ninjanumabbr[-1+11]= ninjaMP ( eps23 , ninjaA0l2 ) ; 
  ninjanumabbr[-1+12]= ninjaMP ( eps12 , ninjaA0l1 ) ; 
  ninjanumabbr[-1+13]= ninjaMP ( ninjaE3 , eps21 ) ; 
  ninjanumabbr[-1+14]= ninjaMP ( ninjaE3 , eps32 ) ; 
  ninjanumabbr[-1+15]= ninjaMP ( ninjaE3 , eps43 ) ; 
  ninjanumabbr[-1+16]= ninjaMP ( ninjaE3 , eps54 ) ; 
  ninjanumabbr[-1+17]= ninjaMP ( ninjaE3 , eps65 ) ; 
  ninjanumabbr[-1+18]= ninjaMP ( eps16 , ninjaA0l6 ) ; 
  ninjanumabbr[-1+19]= ninjaMP ( ninjaE3 , eps16 ) ; 
  ninjanumabbr[-1+20]= ninjaMP ( eps65 , ninjaA0l5 ) ; 
  ninjanumabbr[-1+21]= ninjaMP ( eps54 , ninjaA0l4 ) ; 
  ninjanumabbr[-1+22]= ninjaMP ( eps43 , ninjaA0l3 ) ; 
  ninjanumabbr[-1+23]= ninjaMP ( eps32 , ninjaA0l2 ) ; 
  ninjanumabbr[-1+24]= ninjaMP ( eps21 , ninjaA0l1 ) ; 
  ninjanumabbr[-1+25]= ninjaMP ( ninjaA1 , eps12 ) ; 
  ninjanumabbr[-1+26]= ninjaMP ( ninjaA1 , eps23 ) ; 
  ninjanumabbr[-1+27]= ninjaMP ( ninjaA1 , eps34 ) ; 
  ninjanumabbr[-1+28]= ninjaMP ( ninjaA1 , eps45 ) ; 
  ninjanumabbr[-1+29]= ninjaMP ( ninjaA1 , eps56 ) ; 
  ninjanumabbr[-1+30]= ninjaMP ( ninjaA1 , eps61 ) ; 
  ninjanumabbr[-1+31]= ninjaMP ( ninjaA1 , eps21 ) ; 
  ninjanumabbr[-1+32]= ninjaMP ( ninjaA1 , eps32 ) ; 
  ninjanumabbr[-1+33]= ninjaMP ( ninjaA1 , eps43 ) ; 
  ninjanumabbr[-1+34]= ninjaMP ( ninjaA1 , eps54 ) ; 
  ninjanumabbr[-1+35]= ninjaMP ( ninjaA1 , eps65 ) ; 
  ninjanumabbr[-1+36]= ninjaMP ( ninjaA1 , eps16 ) ; 
  ninjanumabbr[-1+37]= - ninjanumabbr[-1+18]* ninjanumabbr[-1+16]; 
  ninjanumabbr[-1+38]= - ninjanumabbr[-1+21]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]+ ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+16]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+39]= - ninjanumabbr[-1+24]* ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+39]+ ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+17]* ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+39]* ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+40]= ninjanumabbr[-1+38]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+17]* ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+23]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+43]= ninjanumabbr[-1+40]* ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+44]= - ninjanumabbr[-1+20]* ninjanumabbr[-1+43]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+42]+ 
 ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+15]* ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+40]= ninjanumabbr[-1+40]* ninjanumabbr[-1+39]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+22]* ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+44]= - ninjanumabbr[-1+6]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+45]= - ninjanumabbr[-1+7]* ninjanumabbr[-1+10]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+45]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+4]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+45]= ninjanumabbr[-1+7]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+46]= - ninjanumabbr[-1+9]* ninjanumabbr[-1+45]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+46]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+2]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+46]= ninjanumabbr[-1+45]* ninjanumabbr[-1+4]; 
  ninjanumabbr[-1+47]= - ninjanumabbr[-1+11]* ninjanumabbr[-1+46]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+47]+ ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+1]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+47]= ninjanumabbr[-1+2]* ninjanumabbr[-1+46]; 
  ninjanumabbr[-1+48]= - ninjanumabbr[-1+12]* ninjanumabbr[-1+47]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+48]+ ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+44]= ninjanumabbr[-1+5]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+48]= ninjanumabbr[-1+47]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+49]= - ninjanumabbr[-1+8]* ninjanumabbr[-1+48]; 
  ninjanumabbr[-1+37]= ninjanumabbr[-1+37]+ ninjanumabbr[-1+44]+ 
 ninjanumabbr[-1+42]+ ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+37]= NINJA_REAL(64)* ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+34]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+44]= - ninjanumabbr[-1+36]* ninjanumabbr[-1+16]; 
  ninjanumabbr[-1+42]= ninjanumabbr[-1+44]+ ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+42]= ninjanumabbr[-1+13]* ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+38]= - ninjanumabbr[-1+31]* ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+38]+ ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+38]* ninjanumabbr[-1+39]; 
  ninjanumabbr[-1+39]= - ninjanumabbr[-1+35]* ninjanumabbr[-1+43]; 
  ninjanumabbr[-1+41]= - ninjanumabbr[-1+32]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+41]+ ninjanumabbr[-1+38]+ 
 ninjanumabbr[-1+39]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+15]* ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+39]= - ninjanumabbr[-1+33]* ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+41]= - ninjanumabbr[-1+27]* ninjanumabbr[-1+7]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+30]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+42]+ ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+4]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+28]* ninjanumabbr[-1+45]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+42]+ ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+2]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+26]* ninjanumabbr[-1+46]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+42]+ ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+1]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+25]* ninjanumabbr[-1+47]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+41]+ ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+41]= ninjanumabbr[-1+5]* ninjanumabbr[-1+41]; 
  ninjanumabbr[-1+42]= - ninjanumabbr[-1+29]* ninjanumabbr[-1+48]; 
  ninjanumabbr[-1+38]= ninjanumabbr[-1+38]+ ninjanumabbr[-1+41]+ 
 ninjanumabbr[-1+39]+ ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+38]= NINJA_REAL(64)* ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+39]= - ninjanumabbr[-1+15]* ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+40]= - ninjanumabbr[-1+5]* ninjanumabbr[-1+48]; 
  ninjanumabbr[-1+39]= ninjanumabbr[-1+40]+ ninjanumabbr[-1+39]; 
  ninjanumabbr[-1+39]= NINJA_REAL(64)* ninjanumabbr[-1+39]; 
  
 ninjaC[0+ninjaidxt2x0mu0]= 
 ninjanumabbr[-1+39]; 
  
 ninjaC[0+ninjaidxt1x0mu0]= 
 ninjanumabbr[-1+37]; 
  
 ninjaC[0+ninjaidxt1x1mu0]= 
 ninjanumabbr[-1+38]; 
      }
    if (ninja_mindeg > 1+NINJA_RANK_MINUS_N) {
NinjaAbbrType ninjanumabbr[87];  (void)(ninjanumabbr);
  
 ninjanumabbr[-1+1]= ninjaMP ( ninjaA1 , eps12 ) ; 
  ninjanumabbr[-1+2]= ninjaMP ( ninjaE3 , eps23 ) ; 
  ninjanumabbr[-1+3]= ninjaMP ( ninjaE3 , eps34 ) ; 
  ninjanumabbr[-1+4]= ninjaMP ( ninjaE3 , eps45 ) ; 
  ninjanumabbr[-1+5]= ninjaMP ( ninjaE3 , eps56 ) ; 
  ninjanumabbr[-1+6]= ninjaMP ( eps61 , ninjaA0l6 ) ; 
  ninjanumabbr[-1+7]= ninjaMP ( ninjaE3 , eps61 ) ; 
  ninjanumabbr[-1+8]= ninjaMP ( eps56 , ninjaA0l5 ) ; 
  ninjanumabbr[-1+9]= ninjaMP ( eps45 , ninjaA0l4 ) ; 
  ninjanumabbr[-1+10]= ninjaMP ( eps34 , ninjaA0l3 ) ; 
  ninjanumabbr[-1+11]= ninjaMP ( eps23 , ninjaA0l2 ) ; 
  ninjanumabbr[-1+12]= ninjaMP ( ninjaA1 , eps23 ) ; 
  ninjanumabbr[-1+13]= ninjaMP ( ninjaE3 , eps12 ) ; 
  ninjanumabbr[-1+14]= ninjaMP ( eps12 , ninjaA0l1 ) ; 
  ninjanumabbr[-1+15]= ninjaMP ( ninjaA1 , eps34 ) ; 
  ninjanumabbr[-1+16]= ninjaMP ( ninjaA1 , eps45 ) ; 
  ninjanumabbr[-1+17]= ninjaMP ( ninjaA1 , eps56 ) ; 
  ninjanumabbr[-1+18]= ninjaMP ( ninjaA1 , eps61 ) ; 
  ninjanumabbr[-1+19]= ninjaMP ( ninjaA1 , eps21 ) ; 
  ninjanumabbr[-1+20]= ninjaMP ( ninjaE3 , eps32 ) ; 
  ninjanumabbr[-1+21]= ninjaMP ( ninjaE3 , eps43 ) ; 
  ninjanumabbr[-1+22]= ninjaMP ( ninjaE3 , eps54 ) ; 
  ninjanumabbr[-1+23]= ninjaMP ( ninjaE3 , eps65 ) ; 
  ninjanumabbr[-1+24]= ninjaMP ( eps16 , ninjaA0l6 ) ; 
  ninjanumabbr[-1+25]= ninjaMP ( ninjaE3 , eps16 ) ; 
  ninjanumabbr[-1+26]= ninjaMP ( eps65 , ninjaA0l5 ) ; 
  ninjanumabbr[-1+27]= ninjaMP ( eps54 , ninjaA0l4 ) ; 
  ninjanumabbr[-1+28]= ninjaMP ( eps43 , ninjaA0l3 ) ; 
  ninjanumabbr[-1+29]= ninjaMP ( eps32 , ninjaA0l2 ) ; 
  ninjanumabbr[-1+30]= ninjaMP ( ninjaA1 , eps32 ) ; 
  ninjanumabbr[-1+31]= ninjaMP ( ninjaE3 , eps21 ) ; 
  ninjanumabbr[-1+32]= ninjaMP ( eps21 , ninjaA0l1 ) ; 
  ninjanumabbr[-1+33]= ninjaMP ( ninjaA1 , eps43 ) ; 
  ninjanumabbr[-1+34]= ninjaMP ( ninjaA1 , eps54 ) ; 
  ninjanumabbr[-1+35]= ninjaMP ( ninjaA1 , eps65 ) ; 
  ninjanumabbr[-1+36]= ninjaMP ( ninjaA1 , eps16 ) ; 
  ninjanumabbr[-1+37]= ninjaMP ( ninjaE4 , eps61 ) ; 
  ninjanumabbr[-1+38]= ninjaMP ( ninjaE4 , eps56 ) ; 
  ninjanumabbr[-1+39]= ninjaMP ( ninjaE4 , eps45 ) ; 
  ninjanumabbr[-1+40]= ninjaMP ( ninjaE4 , eps34 ) ; 
  ninjanumabbr[-1+41]= ninjaMP ( ninjaE4 , eps23 ) ; 
  ninjanumabbr[-1+42]= ninjaMP ( ninjaE4 , eps12 ) ; 
  ninjanumabbr[-1+43]= ninjaMP ( ninjaE4 , eps16 ) ; 
  ninjanumabbr[-1+44]= ninjaMP ( ninjaE4 , eps65 ) ; 
  ninjanumabbr[-1+45]= ninjaMP ( ninjaE4 , eps54 ) ; 
  ninjanumabbr[-1+46]= ninjaMP ( ninjaE4 , eps43 ) ; 
  ninjanumabbr[-1+47]= ninjaMP ( ninjaE4 , eps32 ) ; 
  ninjanumabbr[-1+48]= ninjaMP ( ninjaE4 , eps21 ) ; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+21]* ninjanumabbr[-1+22]; 
  ninjanumabbr[-1+50]= ninjanumabbr[-1+49]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+51]= ninjanumabbr[-1+50]* ninjanumabbr[-1+48]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+31]* ninjanumabbr[-1+21]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+52]* ninjanumabbr[-1+22]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+53]* ninjanumabbr[-1+44]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+31]* ninjanumabbr[-1+22]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+55]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+57]= ninjanumabbr[-1+56]* ninjanumabbr[-1+46]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+52]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+58]* ninjanumabbr[-1+45]; 
  ninjanumabbr[-1+51]= ninjanumabbr[-1+57]+ ninjanumabbr[-1+51]+ 
 ninjanumabbr[-1+54]+ ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+54]= - ninjaP1 * ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+57]= ninjanumabbr[-1+23]* ninjanumabbr[-1+31]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+57]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+60]= - ninjanumabbr[-1+26]* ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+61]= ninjanumabbr[-1+23]* ninjanumabbr[-1+21]; 
  ninjanumabbr[-1+62]= - ninjanumabbr[-1+32]* ninjanumabbr[-1+61]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+62]+ ninjanumabbr[-1+60]- 
 ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+34]* ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+60]= ninjanumabbr[-1+57]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+62]= - ninjanumabbr[-1+26]* ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+63]= ninjanumabbr[-1+23]* ninjanumabbr[-1+22]; 
  ninjanumabbr[-1+64]= - ninjanumabbr[-1+32]* ninjanumabbr[-1+63]; 
  ninjanumabbr[-1+62]= ninjanumabbr[-1+64]+ ninjanumabbr[-1+62]- 
 ninjanumabbr[-1+60]; 
  ninjanumabbr[-1+62]= ninjanumabbr[-1+33]* ninjanumabbr[-1+62]; 
  ninjanumabbr[-1+64]= ninjanumabbr[-1+22]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+27]* ninjanumabbr[-1+21]; 
  ninjanumabbr[-1+64]= ninjanumabbr[-1+64]+ ninjanumabbr[-1+65]; 
  ninjanumabbr[-1+64]= ninjanumabbr[-1+64]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+49]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+64]= ninjanumabbr[-1+64]+ ninjanumabbr[-1+65]; 
  ninjanumabbr[-1+65]= - ninjanumabbr[-1+19]* ninjanumabbr[-1+64]; 
  ninjanumabbr[-1+66]= ninjanumabbr[-1+52]* ninjanumabbr[-1+27]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+55]* ninjanumabbr[-1+28]; 
  ninjanumabbr[-1+66]= ninjanumabbr[-1+66]+ ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+67]= - ninjanumabbr[-1+32]* ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+67]- ninjanumabbr[-1+66]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+35]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]+ ninjanumabbr[-1+62]+ 
 ninjanumabbr[-1+67]+ ninjanumabbr[-1+65]+ ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+25]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+50]* ninjanumabbr[-1+19]; 
  ninjanumabbr[-1+62]= ninjanumabbr[-1+53]* ninjanumabbr[-1+35]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+56]* ninjanumabbr[-1+33]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+58]* ninjanumabbr[-1+34]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+56]+ ninjanumabbr[-1+62]+ 
 ninjanumabbr[-1+59]+ ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+58]= - ninjanumabbr[-1+24]* ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+66]* ninjanumabbr[-1+23]; 
  ninjanumabbr[-1+50]= ninjanumabbr[-1+50]* ninjanumabbr[-1+32]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]* ninjanumabbr[-1+26]; 
  ninjanumabbr[-1+50]= ninjanumabbr[-1+59]+ ninjanumabbr[-1+50]+ 
 ninjanumabbr[-1+53]; 
  ninjanumabbr[-1+53]= - ninjanumabbr[-1+36]* ninjanumabbr[-1+50]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+63]* ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+62]= ninjanumabbr[-1+59]* ninjanumabbr[-1+43]; 
  ninjanumabbr[-1+65]= - ninjaP1 * ninjanumabbr[-1+62]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+65]+ ninjanumabbr[-1+54]+ 
 ninjanumabbr[-1+58]+ ninjanumabbr[-1+53]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+20]* ninjanumabbr[-1+53]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+2]* ninjanumabbr[-1+8]; 
  ninjanumabbr[-1+58]= - ninjanumabbr[-1+11]* ninjanumabbr[-1+5]; 
  ninjanumabbr[-1+54]= - ninjanumabbr[-1+54]+ ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+18]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+5]* ninjanumabbr[-1+6]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+7]* ninjanumabbr[-1+8]; 
  ninjanumabbr[-1+58]= ninjanumabbr[-1+58]+ ninjanumabbr[-1+65]; 
  ninjanumabbr[-1+65]= - ninjanumabbr[-1+12]* ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+65]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+3]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+7]* ninjanumabbr[-1+5]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+65]* ninjanumabbr[-1+11]; 
  ninjanumabbr[-1+68]= ninjanumabbr[-1+7]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+69]= ninjanumabbr[-1+68]* ninjanumabbr[-1+8]; 
  ninjanumabbr[-1+70]= ninjanumabbr[-1+5]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+71]= ninjanumabbr[-1+70]* ninjanumabbr[-1+6]; 
  ninjanumabbr[-1+67]= ninjanumabbr[-1+71]+ ninjanumabbr[-1+67]+ 
 ninjanumabbr[-1+69]; 
  ninjanumabbr[-1+69]= - ninjanumabbr[-1+15]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+71]= ninjanumabbr[-1+65]* ninjanumabbr[-1+12]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+70]* ninjanumabbr[-1+18]; 
  ninjanumabbr[-1+71]= ninjanumabbr[-1+71]+ ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+72]= - ninjanumabbr[-1+10]* ninjanumabbr[-1+71]; 
  ninjanumabbr[-1+73]= ninjanumabbr[-1+6]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+74]= - ninjanumabbr[-1+11]* ninjanumabbr[-1+7]; 
  ninjanumabbr[-1+74]= - ninjanumabbr[-1+73]+ ninjanumabbr[-1+74]; 
  ninjanumabbr[-1+74]= ninjanumabbr[-1+3]* ninjanumabbr[-1+74]; 
  ninjanumabbr[-1+75]= - ninjanumabbr[-1+10]* ninjanumabbr[-1+68]; 
  ninjanumabbr[-1+74]= ninjanumabbr[-1+74]+ ninjanumabbr[-1+75]; 
  ninjanumabbr[-1+74]= ninjanumabbr[-1+17]* ninjanumabbr[-1+74]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+69]+ ninjanumabbr[-1+74]+ 
 ninjanumabbr[-1+54]+ ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+13]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+69]= ninjanumabbr[-1+71]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+65]* ninjanumabbr[-1+2]; 
  ninjanumabbr[-1+74]= ninjanumabbr[-1+72]* ninjanumabbr[-1+15]; 
  ninjanumabbr[-1+75]= ninjanumabbr[-1+68]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+76]= ninjanumabbr[-1+75]* ninjanumabbr[-1+17]; 
  ninjanumabbr[-1+69]= ninjanumabbr[-1+74]+ ninjanumabbr[-1+76]+ 
 ninjanumabbr[-1+69]; 
  ninjanumabbr[-1+74]= - ninjanumabbr[-1+14]* ninjanumabbr[-1+69]; 
  ninjanumabbr[-1+76]= ninjanumabbr[-1+67]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+77]= ninjanumabbr[-1+72]* ninjanumabbr[-1+10]; 
  ninjanumabbr[-1+76]= ninjanumabbr[-1+77]+ ninjanumabbr[-1+76]; 
  ninjanumabbr[-1+77]= - ninjanumabbr[-1+1]* ninjanumabbr[-1+76]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]+ ninjanumabbr[-1+77]+ 
 ninjanumabbr[-1+74]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+4]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+74]= ninjanumabbr[-1+4]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+41]* ninjanumabbr[-1+74]* ninjanumabbr[-1+65]* 
 ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+77]= ninjanumabbr[-1+72]* ninjanumabbr[-1+3]; 
  ninjanumabbr[-1+78]= ninjanumabbr[-1+39]* ninjanumabbr[-1+77]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+79]= ninjanumabbr[-1+4]* ninjanumabbr[-1+77]* ninjanumabbr[-1+42]; 
  ninjanumabbr[-1+65]= ninjanumabbr[-1+78]+ ninjanumabbr[-1+65]+ 
 ninjanumabbr[-1+79]; 
  ninjanumabbr[-1+70]= ninjanumabbr[-1+3]* ninjanumabbr[-1+70]* ninjanumabbr[-1+37]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+72]* ninjanumabbr[-1+40]; 
  ninjanumabbr[-1+75]= ninjanumabbr[-1+75]* ninjanumabbr[-1+38]; 
  ninjanumabbr[-1+70]= ninjanumabbr[-1+70]+ ninjanumabbr[-1+72]+ 
 ninjanumabbr[-1+75]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+70]* ninjanumabbr[-1+74]; 
  ninjanumabbr[-1+72]= ninjanumabbr[-1+72]+ ninjanumabbr[-1+65]; 
  ninjanumabbr[-1+74]= - ninjaP1 * ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+75]= - ninjanumabbr[-1+29]* ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+78]= - ninjanumabbr[-1+30]* ninjanumabbr[-1+50]; 
  ninjanumabbr[-1+79]= ninjanumabbr[-1+59]* ninjanumabbr[-1+47]; 
  ninjanumabbr[-1+80]= - ninjaP1 * ninjanumabbr[-1+79]; 
  ninjanumabbr[-1+75]= ninjanumabbr[-1+80]+ ninjanumabbr[-1+78]+ 
 ninjanumabbr[-1+75]; 
  ninjanumabbr[-1+75]= ninjanumabbr[-1+25]* ninjanumabbr[-1+75]; 
  ninjanumabbr[-1+78]= ninjanumabbr[-1+69]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+80]= - ninjanumabbr[-1+9]* ninjanumabbr[-1+78]; 
  ninjanumabbr[-1+81]= ninjanumabbr[-1+76]* ninjanumabbr[-1+13]; 
  ninjanumabbr[-1+82]= ninjanumabbr[-1+77]* ninjanumabbr[-1+14]; 
  ninjanumabbr[-1+82]= - ninjanumabbr[-1+82]- ninjanumabbr[-1+81]; 
  ninjanumabbr[-1+82]= ninjanumabbr[-1+16]* ninjanumabbr[-1+82]; 
  ninjanumabbr[-1+83]= ninjanumabbr[-1+59]* ninjanumabbr[-1+36]; 
  ninjanumabbr[-1+84]= - ninjanumabbr[-1+29]* ninjanumabbr[-1+83]; 
  ninjanumabbr[-1+59]= ninjanumabbr[-1+59]* ninjanumabbr[-1+24]; 
  ninjanumabbr[-1+85]= - ninjanumabbr[-1+30]* ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+86]= ninjanumabbr[-1+77]* ninjanumabbr[-1+9]; 
  ninjanumabbr[-1+87]= - ninjanumabbr[-1+1]* ninjanumabbr[-1+86]; 
  ninjanumabbr[-1+53]= ninjanumabbr[-1+53]+ ninjanumabbr[-1+75]+ 
 ninjanumabbr[-1+82]+ ninjanumabbr[-1+54]+ ninjanumabbr[-1+80]+ 
 ninjanumabbr[-1+85]+ ninjanumabbr[-1+84]+ ninjanumabbr[-1+87]+ 
 ninjanumabbr[-1+74]; 
  ninjanumabbr[-1+53]= NINJA_REAL(64)* ninjanumabbr[-1+53]; 
  ninjanumabbr[-1+54]= - ninjanumabbr[-1+36]* ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+74]= - ninjaP2 * ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+57]= - ninjanumabbr[-1+34]* ninjanumabbr[-1+57]; 
  ninjanumabbr[-1+63]= - ninjanumabbr[-1+19]* ninjanumabbr[-1+63]; 
  ninjanumabbr[-1+55]= - ninjanumabbr[-1+35]* ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+55]+ ninjanumabbr[-1+57]+ 
 ninjanumabbr[-1+63]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+33]* ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+52]= - ninjanumabbr[-1+34]* ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+49]= - ninjanumabbr[-1+19]* ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+52]+ ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+35]* ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+52]= - ninjanumabbr[-1+19]* ninjanumabbr[-1+34]* 
 ninjanumabbr[-1+61]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+55]+ ninjanumabbr[-1+49]+ 
 ninjanumabbr[-1+52]+ ninjanumabbr[-1+74]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+25]* ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+52]= - ninjaP2 * ninjanumabbr[-1+62]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+52]+ ninjanumabbr[-1+49]+ 
 ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+20]* ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+52]= - ninjaP2 * ninjanumabbr[-1+70]; 
  ninjanumabbr[-1+54]= - ninjanumabbr[-1+2]* ninjanumabbr[-1+18]; 
  ninjanumabbr[-1+55]= - ninjanumabbr[-1+12]* ninjanumabbr[-1+7]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+54]+ ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+17]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+55]= - ninjanumabbr[-1+12]* ninjanumabbr[-1+5]* 
 ninjanumabbr[-1+18]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+55]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+3]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+55]= - ninjanumabbr[-1+17]* ninjanumabbr[-1+68]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+55]- ninjanumabbr[-1+71]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+15]* ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+55]+ ninjanumabbr[-1+52]+ 
 ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+13]* ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+54]= - ninjanumabbr[-1+1]* ninjanumabbr[-1+69]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+52]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+4]* ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+54]= - ninjanumabbr[-1+30]* ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+55]= - ninjaP2 * ninjanumabbr[-1+79]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+55]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+54]= ninjanumabbr[-1+25]* ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+55]= - ninjaP2 * ninjanumabbr[-1+65]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+77]* ninjanumabbr[-1+1]; 
  ninjanumabbr[-1+56]= - ninjanumabbr[-1+56]- ninjanumabbr[-1+78]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+16]* ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+57]= - ninjanumabbr[-1+30]* ninjanumabbr[-1+83]; 
  ninjanumabbr[-1+49]= ninjanumabbr[-1+49]+ ninjanumabbr[-1+54]+ 
 ninjanumabbr[-1+56]+ ninjanumabbr[-1+52]+ ninjanumabbr[-1+57]+ 
 ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+49]= NINJA_REAL(64)* ninjanumabbr[-1+49]; 
  ninjanumabbr[-1+52]= - ninjanumabbr[-1+25]* ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+52]- ninjanumabbr[-1+62]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+20]* ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+54]= - ninjanumabbr[-1+25]* ninjanumabbr[-1+79]; 
  ninjanumabbr[-1+52]= ninjanumabbr[-1+52]+ ninjanumabbr[-1+54]- 
 ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+52]= NINJA_REAL(64)* ninjanumabbr[-1+52]; 
  ninjanumabbr[-1+54]= - ninjaP0 * ninjanumabbr[-1+72]; 
  ninjanumabbr[-1+55]= - ninjanumabbr[-1+14]* ninjanumabbr[-1+76]; 
  ninjanumabbr[-1+56]= - ninjanumabbr[-1+10]* ninjanumabbr[-1+67]; 
  ninjanumabbr[-1+57]= - ninjanumabbr[-1+11]* ninjanumabbr[-1+58]; 
  ninjanumabbr[-1+58]= - ninjanumabbr[-1+8]* ninjanumabbr[-1+73]; 
  ninjanumabbr[-1+57]= ninjanumabbr[-1+58]+ ninjanumabbr[-1+57]; 
  ninjanumabbr[-1+57]= ninjanumabbr[-1+3]* ninjanumabbr[-1+57]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+57]+ ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+56]= ninjanumabbr[-1+13]* ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+55]+ ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+55]= ninjanumabbr[-1+4]* ninjanumabbr[-1+55]; 
  ninjanumabbr[-1+51]= - ninjaP0 * ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+56]= - ninjanumabbr[-1+26]* ninjanumabbr[-1+66]; 
  ninjanumabbr[-1+57]= - ninjanumabbr[-1+32]* ninjanumabbr[-1+64]; 
  ninjanumabbr[-1+58]= - ninjanumabbr[-1+28]* ninjanumabbr[-1+60]; 
  ninjanumabbr[-1+51]= ninjanumabbr[-1+51]+ ninjanumabbr[-1+57]+ 
 ninjanumabbr[-1+58]+ ninjanumabbr[-1+56]; 
  ninjanumabbr[-1+51]= ninjanumabbr[-1+25]* ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+56]= - ninjanumabbr[-1+24]* ninjanumabbr[-1+50]; 
  ninjanumabbr[-1+57]= - ninjaP0 * ninjanumabbr[-1+62]; 
  ninjanumabbr[-1+51]= ninjanumabbr[-1+57]+ ninjanumabbr[-1+56]+ 
 ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+51]= ninjanumabbr[-1+20]* ninjanumabbr[-1+51]; 
  ninjanumabbr[-1+56]= - ninjanumabbr[-1+9]* ninjanumabbr[-1+81]; 
  ninjanumabbr[-1+50]= - ninjanumabbr[-1+29]* ninjanumabbr[-1+50]; 
  ninjanumabbr[-1+57]= - ninjaP0 * ninjanumabbr[-1+79]; 
  ninjanumabbr[-1+50]= ninjanumabbr[-1+57]+ ninjanumabbr[-1+50]; 
  ninjanumabbr[-1+50]= ninjanumabbr[-1+25]* ninjanumabbr[-1+50]; 
  ninjanumabbr[-1+57]= - ninjanumabbr[-1+29]* ninjanumabbr[-1+59]; 
  ninjanumabbr[-1+58]= - ninjanumabbr[-1+14]* ninjanumabbr[-1+86]; 
  ninjanumabbr[-1+50]= ninjanumabbr[-1+51]+ ninjanumabbr[-1+50]+ 
 ninjanumabbr[-1+55]+ ninjanumabbr[-1+56]+ ninjanumabbr[-1+58]+ 
 ninjanumabbr[-1+57]+ ninjanumabbr[-1+54]; 
  ninjanumabbr[-1+50]= NINJA_REAL(64)* ninjanumabbr[-1+50]; 
  
 ninjaC[0+ninjaidxt0x0mu0]= 
 ninjanumabbr[-1+50]; 
  
 ninjaC[0+ninjaidxt0x0mu2]= 
 ninjanumabbr[-1+52]; 
  
 ninjaC[0+ninjaidxt0x1mu0]= 
 ninjanumabbr[-1+53]; 
  
 ninjaC[0+ninjaidxt0x2mu0]= 
 ninjanumabbr[-1+49]; 
      }
  }

#if NINJA_NUM_NAMESPACE
} // namespace NINJA_NUM_NAMESPACE
#endif
