// This -*- C++ -*- file has been generated by the Python package
// NinjaNumGen, which is distributed with the Ninja library.

#include "ttbarh_num.hh"

#include <ninja/num_defs.hh>
#include <ninja/ninjanumgen.hh>

#define NINJA_NUM TTbarHDiagram
#define NINJA_RANK_MINUS_N (-1)
#define NINJA_NUM_NAMESPACE 0

#if NINJA_NUM_NAMESPACE
namespace NINJA_NUM_NAMESPACE {
#endif

  ninja::Complex NINJA_NUM::evaluate(const ninja::ComplexMomentum & ninjaQ,
									 const ninja::Complex & ninjaMu2,
									 int ninja_cut,
									 const ninja::PartitionInt ninja_cutidx[])
  {
	ninja::Complex ninja_result;
    (void)(ninjaQ);
	(void)(ninjaMu2);
	(void)(ninja_cut);
	(void)(ninja_cutidx);
    NinjaAbbrType ninjanumabbr[130];  (void)(ninjanumabbr);
  
    ninjanumabbr[-1+1]= ninjaMP ( ninjaQ , ninjaQ ) ; 
    ninjanumabbr[-1+2]= globabbr ( 75 ) ; 
    ninjanumabbr[-1+3]= ninjaMP ( ninjaQ , k1 ) ; 
    ninjanumabbr[-1+4]= globabbr ( 59 ) ; 
    ninjanumabbr[-1+5]= ninjaMP ( ninjaQ , k2 ) ; 
    ninjanumabbr[-1+6]= globabbr ( 11 ) ; 
    ninjanumabbr[-1+7]= ninjaMP ( ninjaQ , l4 ) ; 
    ninjanumabbr[-1+8]= globabbr ( 62 ) ; 
    ninjanumabbr[-1+9]= ninjaMP ( ninjaQ , l5 ) ; 
    ninjanumabbr[-1+10]= globabbr ( 8 ) ; 
    ninjanumabbr[-1+11]= ninjaMP ( ninjaQ , e1 ) ; 
    ninjanumabbr[-1+12]= ninjaMP ( ninjaQ , e2 ) ; 
    ninjanumabbr[-1+13]= globabbr ( 53 ) ; 
    ninjanumabbr[-1+14]= ninjaMP ( ninjaQ , spvae2k2 ) ; 
    ninjanumabbr[-1+15]= globabbr ( 32 ) ; 
    ninjanumabbr[-1+16]= ninjaMP ( ninjaQ , spval5e2 ) ; 
    ninjanumabbr[-1+17]= globabbr ( 102 ) ; 
    ninjanumabbr[-1+18]= globabbr ( 36 ) ; 
    ninjanumabbr[-1+19]= ninjaMP ( ninjaQ , spvae1k2 ) ; 
    ninjanumabbr[-1+20]= globabbr ( 24 ) ; 
    ninjanumabbr[-1+21]= ninjaMP ( ninjaQ , spval5e1 ) ; 
    ninjanumabbr[-1+22]= globabbr ( 12 ) ; 
    ninjanumabbr[-1+23]= globabbr ( 25 ) ; 
    ninjanumabbr[-1+24]= ninjaMP ( ninjaQ , spvak1k2 ) ; 
    ninjanumabbr[-1+25]= globabbr ( 41 ) ; 
    ninjanumabbr[-1+26]= ninjaMP ( ninjaQ , spval5k1 ) ; 
    ninjanumabbr[-1+27]= globabbr ( 55 ) ; 
    ninjanumabbr[-1+28]= ninjaMP ( ninjaQ , spval5k2 ) ; 
    ninjanumabbr[-1+29]= globabbr ( 51 ) ; 
    ninjanumabbr[-1+30]= ninjaMP ( ninjaQ , spval5l4 ) ; 
    ninjanumabbr[-1+31]= globabbr ( 49 ) ; 
    ninjanumabbr[-1+32]= globabbr ( 20 ) ; 
    ninjanumabbr[-1+33]= globabbr ( 10 ) ; 
    ninjanumabbr[-1+34]= globabbr ( 13 ) ; 
    ninjanumabbr[-1+35]= globabbr ( 133 ) ; 
    ninjanumabbr[-1+36]= globabbr ( 72 ) ; 
    ninjanumabbr[-1+37]= globabbr ( 140 ) ; 
    ninjanumabbr[-1+38]= globabbr ( 123 ) ; 
    ninjanumabbr[-1+39]= globabbr ( 19 ) ; 
    ninjanumabbr[-1+40]= globabbr ( 97 ) ; 
    ninjanumabbr[-1+41]= globabbr ( 115 ) ; 
    ninjanumabbr[-1+42]= globabbr ( 54 ) ; 
    ninjanumabbr[-1+43]= globabbr ( 126 ) ; 
    ninjanumabbr[-1+44]= globabbr ( 40 ) ; 
    ninjanumabbr[-1+45]= globabbr ( 77 ) ; 
    ninjanumabbr[-1+46]= globabbr ( 88 ) ; 
    ninjanumabbr[-1+47]= globabbr ( 81 ) ; 
    ninjanumabbr[-1+48]= globabbr ( 21 ) ; 
    ninjanumabbr[-1+49]= globabbr ( 6 ) ; 
    ninjanumabbr[-1+50]= globabbr ( 137 ) ; 
    ninjanumabbr[-1+51]= globabbr ( 96 ) ; 
    ninjanumabbr[-1+52]= globabbr ( 52 ) ; 
    ninjanumabbr[-1+53]= globabbr ( 86 ) ; 
    ninjanumabbr[-1+54]= globabbr ( 45 ) ; 
    ninjanumabbr[-1+55]= globabbr ( 50 ) ; 
    ninjanumabbr[-1+56]= globabbr ( 63 ) ; 
    ninjanumabbr[-1+57]= globabbr ( 84 ) ; 
    ninjanumabbr[-1+58]= globabbr ( 39 ) ; 
    ninjanumabbr[-1+59]= globabbr ( 56 ) ; 
    ninjanumabbr[-1+60]= globabbr ( 37 ) ; 
    ninjanumabbr[-1+61]= globabbr ( 153 ) ; 
    ninjanumabbr[-1+62]= globabbr ( 47 ) ; 
    ninjanumabbr[-1+63]= globabbr ( 22 ) ; 
    ninjanumabbr[-1+64]= globabbr ( 132 ) ; 
    ninjanumabbr[-1+65]= globabbr ( 146 ) ; 
    ninjanumabbr[-1+66]= globabbr ( 143 ) ; 
    ninjanumabbr[-1+67]= globabbr ( 104 ) ; 
    ninjanumabbr[-1+68]= globabbr ( 26 ) ; 
    ninjanumabbr[-1+69]= globabbr ( 58 ) ; 
    ninjanumabbr[-1+70]= globabbr ( 87 ) ; 
    ninjanumabbr[-1+71]= globabbr ( 100 ) ; 
    ninjanumabbr[-1+72]= globabbr ( 42 ) ; 
    ninjanumabbr[-1+73]= globabbr ( 35 ) ; 
    ninjanumabbr[-1+74]= globabbr ( 34 ) ; 
    ninjanumabbr[-1+75]= globabbr ( 7 ) ; 
    ninjanumabbr[-1+76]= globabbr ( 91 ) ; 
    ninjanumabbr[-1+77]= globabbr ( 131 ) ; 
    ninjanumabbr[-1+78]= globabbr ( 129 ) ; 
    ninjanumabbr[-1+79]= globabbr ( 79 ) ; 
    ninjanumabbr[-1+80]= globabbr ( 120 ) ; 
    ninjanumabbr[-1+81]= globabbr ( 31 ) ; 
    ninjanumabbr[-1+82]= ninjaMP ( ninjaQ , spvak1l4 ) ; 
    ninjanumabbr[-1+83]= globabbr ( 76 ) ; 
    ninjanumabbr[-1+84]= ninjaMP ( ninjaQ , spvak2k1 ) ; 
    ninjanumabbr[-1+85]= globabbr ( 66 ) ; 
    ninjanumabbr[-1+86]= ninjaMP ( ninjaQ , spvak2l4 ) ; 
    ninjanumabbr[-1+87]= globabbr ( 71 ) ; 
    ninjanumabbr[-1+88]= globabbr ( 27 ) ; 
    ninjanumabbr[-1+89]= globabbr ( 38 ) ; 
    ninjanumabbr[-1+90]= globabbr ( 74 ) ; 
    ninjanumabbr[-1+91]= globabbr ( 48 ) ; 
    ninjanumabbr[-1+92]= globabbr ( 29 ) ; 
    ninjanumabbr[-1+93]= ninjaMP ( ninjaQ , spval4k2 ) ; 
    ninjanumabbr[-1+94]= globabbr ( 18 ) ; 
    ninjanumabbr[-1+95]= globabbr ( 23 ) ; 
    ninjanumabbr[-1+96]= globabbr ( 9 ) ; 
    ninjanumabbr[-1+97]= globabbr ( 68 ) ; 
    ninjanumabbr[-1+98]= globabbr ( 33 ) ; 
    ninjanumabbr[-1+99]= globabbr ( 46 ) ; 
    ninjanumabbr[-1+100]= globabbr ( 30 ) ; 
    ninjanumabbr[-1+101]= globabbr ( 14 ) ; 
    ninjanumabbr[-1+102]= globabbr ( 65 ) ; 
    ninjanumabbr[-1+103]= globabbr ( 28 ) ; 
    ninjanumabbr[-1+104]= globabbr ( 60 ) ; 
    ninjanumabbr[-1+105]= globabbr ( 67 ) ; 
    ninjanumabbr[-1+106]= globabbr ( 43 ) ; 
    ninjanumabbr[-1+107]= globabbr ( 73 ) ; 
    ninjanumabbr[-1+108]= globabbr ( 15 ) ; 
    ninjanumabbr[-1+109]= globabbr ( 17 ) ; 
    ninjanumabbr[-1+110]= globabbr ( 16 ) ; 
    ninjanumabbr[-1+111]= globabbr ( 64 ) ; 
    ninjanumabbr[-1+112]= globabbr ( 44 ) ; 
    ninjanumabbr[-1+113]= globabbr ( 92 ) ; 
    ninjanumabbr[-1+114]= globabbr ( 98 ) ; 
    ninjanumabbr[-1+115]= globabbr ( 57 ) ; 
    ninjanumabbr[-1+116]= ninjanumabbr[-1+28]* ninjanumabbr[-1+89]; 
    ninjanumabbr[-1+117]= ninjanumabbr[-1+7]* ninjanumabbr[-1+65]; 
    ninjanumabbr[-1+118]= ninjanumabbr[-1+24]* ninjanumabbr[-1+81]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+85]* ninjanumabbr[-1+84]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+83]* ninjanumabbr[-1+82]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+5]* ninjanumabbr[-1+52]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+13]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+86]* ninjanumabbr[-1+87]; 
    ninjanumabbr[-1+116]= ninjanumabbr[-1+123]+ ninjanumabbr[-1+122]+ 
      ninjanumabbr[-1+121]+ ninjanumabbr[-1+120]+ ninjanumabbr[-1+119]+ 
      ninjanumabbr[-1+118]+ ninjanumabbr[-1+117]+ ninjanumabbr[-1+91]+ 
      ninjanumabbr[-1+116]; 
    ninjanumabbr[-1+116]= ninjanumabbr[-1+11]* ninjanumabbr[-1+116]; 
    ninjanumabbr[-1+117]= ninjanumabbr[-1+5]* ninjanumabbr[-1+58]; 
    ninjanumabbr[-1+118]= ninjanumabbr[-1+101]* ninjanumabbr[-1+24]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+71]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+93]* ninjanumabbr[-1+102]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+23]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+79]* ninjanumabbr[-1+9]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+104]* ninjanumabbr[-1+28]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+11]* ninjanumabbr[-1+88]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+124]+ ninjanumabbr[-1+103]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+26]* ninjanumabbr[-1+124]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+90]* ninjanumabbr[-1+11]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+105]+ ninjanumabbr[-1+125]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+30]* ninjanumabbr[-1+125]; 
    ninjanumabbr[-1+126]= ninjanumabbr[-1+11]* ninjanumabbr[-1+3]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+38]* ninjanumabbr[-1+126]; 
    ninjanumabbr[-1+116]= ninjanumabbr[-1+127]+ ninjanumabbr[-1+125]+ 
      ninjanumabbr[-1+124]+ ninjanumabbr[-1+123]+ ninjanumabbr[-1+122]+ 
      ninjanumabbr[-1+121]+ ninjanumabbr[-1+120]+ ninjanumabbr[-1+119]+ 
      ninjanumabbr[-1+118]+ ninjanumabbr[-1+108]+ ninjanumabbr[-1+117]+ 
      ninjanumabbr[-1+116]; 
    ninjanumabbr[-1+116]= ninjanumabbr[-1+12]* ninjanumabbr[-1+116]; 
    ninjanumabbr[-1+117]= ninjanumabbr[-1+3]- ninjanumabbr[-1+9]; 
    ninjanumabbr[-1+118]= - ninjanumabbr[-1+40]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+67]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+120]= - ninjanumabbr[-1+17]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+118]= ninjanumabbr[-1+120]+ ninjanumabbr[-1+99]+ 
      ninjanumabbr[-1+118]+ ninjanumabbr[-1+119]; 
    ninjanumabbr[-1+118]= ninjanumabbr[-1+16]* ninjanumabbr[-1+118]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+66]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+120]= - ninjanumabbr[-1+15]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+121]= - ninjanumabbr[-1+39]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+121]+ ninjanumabbr[-1+120]+ 
      ninjanumabbr[-1+119]+ ninjanumabbr[-1+98]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+14]* ninjanumabbr[-1+119]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+53]* ninjanumabbr[-1+14]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+54]* ninjanumabbr[-1+16]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+121]+ ninjanumabbr[-1+55]+ 
      ninjanumabbr[-1+120]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+5]* ninjanumabbr[-1+120]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+77]* ninjanumabbr[-1+12]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+121]+ ninjanumabbr[-1+78]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+9]* ninjanumabbr[-1+121]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+68]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+92]* ninjanumabbr[-1+24]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+18]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+93]* ninjanumabbr[-1+94]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+96]* ninjanumabbr[-1+28]; 
    ninjanumabbr[-1+128]= ninjanumabbr[-1+95]* ninjanumabbr[-1+26]; 
    ninjanumabbr[-1+118]= ninjanumabbr[-1+128]+ ninjanumabbr[-1+127]+ 
      ninjanumabbr[-1+125]+ ninjanumabbr[-1+124]+ ninjanumabbr[-1+123]+ 
      ninjanumabbr[-1+122]+ ninjanumabbr[-1+119]+ ninjanumabbr[-1+100]+ 
      ninjanumabbr[-1+118]+ ninjanumabbr[-1+120]+ ninjanumabbr[-1+121]; 
    ninjanumabbr[-1+118]= ninjanumabbr[-1+11]* ninjanumabbr[-1+118]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+4]* ninjanumabbr[-1+3]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+25]* ninjanumabbr[-1+24]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+8]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+29]* ninjanumabbr[-1+28]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+6]* ninjanumabbr[-1+5]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+10]* ninjanumabbr[-1+9]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+124]+ ninjanumabbr[-1+123]+ 
      ninjanumabbr[-1+122]+ ninjanumabbr[-1+121]+ ninjanumabbr[-1+120]+ 
      ninjanumabbr[-1+34]+ ninjanumabbr[-1+119]; 
    ninjanumabbr[-1+119]= ninjanumabbr[-1+1]* ninjanumabbr[-1+119]; 
    ninjanumabbr[-1+120]= - ninjanumabbr[-1+61]* ninjanumabbr[-1+28]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+51]* ninjanumabbr[-1+9]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+50]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+5]* ninjanumabbr[-1+49]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+59]* ninjanumabbr[-1+24]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+124]+ ninjanumabbr[-1+123]+ 
      ninjanumabbr[-1+63]+ ninjanumabbr[-1+122]+ ninjanumabbr[-1+120]+ 
      ninjanumabbr[-1+121]; 
    ninjanumabbr[-1+120]= ninjanumabbr[-1+5]* ninjanumabbr[-1+120]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+7]* ninjanumabbr[-1+75]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+45]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+11]* ninjanumabbr[-1+97]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+62]* ninjanumabbr[-1+5]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+31]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+125]+ ninjanumabbr[-1+124]+ 
      ninjanumabbr[-1+123]+ ninjanumabbr[-1+122]+ ninjanumabbr[-1+121]+ 
      ninjanumabbr[-1+112]; 
    ninjanumabbr[-1+121]= ninjanumabbr[-1+30]* ninjanumabbr[-1+121]; 
    ninjanumabbr[-1+122]= - ninjanumabbr[-1+37]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+123]= - ninjanumabbr[-1+35]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+36]* ninjanumabbr[-1+5]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+44]* ninjanumabbr[-1+12]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+125]+ ninjanumabbr[-1+124]+ 
      ninjanumabbr[-1+48]+ ninjanumabbr[-1+123]+ ninjanumabbr[-1+122]; 
    ninjanumabbr[-1+122]= ninjanumabbr[-1+3]* ninjanumabbr[-1+122]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+7]* ninjanumabbr[-1+70]; 
    ninjanumabbr[-1+124]= - ninjanumabbr[-1+43]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+57]* ninjanumabbr[-1+5]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+22]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+127]+ ninjanumabbr[-1+125]+ 
      ninjanumabbr[-1+124]+ ninjanumabbr[-1+123]+ ninjanumabbr[-1+107]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+12]* ninjanumabbr[-1+123]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+5]- ninjanumabbr[-1+3]; 
    ninjanumabbr[-1+125]= - ninjanumabbr[-1+47]* ninjanumabbr[-1+124]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+33]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+123]+ ninjanumabbr[-1+127]+ 
      ninjanumabbr[-1+114]+ ninjanumabbr[-1+125]; 
    ninjanumabbr[-1+123]= ninjanumabbr[-1+21]* ninjanumabbr[-1+123]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+7]* ninjanumabbr[-1+69]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+20]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+117]= - ninjanumabbr[-1+42]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+128]= ninjanumabbr[-1+56]* ninjanumabbr[-1+5]; 
    ninjanumabbr[-1+117]= ninjanumabbr[-1+128]+ ninjanumabbr[-1+117]+ 
      ninjanumabbr[-1+127]+ ninjanumabbr[-1+125]+ ninjanumabbr[-1+106]; 
    ninjanumabbr[-1+117]= ninjanumabbr[-1+12]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+46]* ninjanumabbr[-1+124]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+32]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+117]= ninjanumabbr[-1+113]+ ninjanumabbr[-1+117]+ 
      ninjanumabbr[-1+125]+ ninjanumabbr[-1+124]; 
    ninjanumabbr[-1+117]= ninjanumabbr[-1+19]* ninjanumabbr[-1+117]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+74]* ninjanumabbr[-1+28]; 
    ninjanumabbr[-1+125]= - ninjanumabbr[-1+64]* ninjanumabbr[-1+9]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+72]* ninjanumabbr[-1+24]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+127]+ ninjanumabbr[-1+125]+ 
      ninjanumabbr[-1+76]+ ninjanumabbr[-1+124]; 
    ninjanumabbr[-1+124]= ninjanumabbr[-1+7]* ninjanumabbr[-1+124]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+5]* ninjanumabbr[-1+60]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+27]* ninjanumabbr[-1+1]; 
    ninjanumabbr[-1+128]= ninjanumabbr[-1+73]* ninjanumabbr[-1+7]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+128]+ ninjanumabbr[-1+127]+ 
      ninjanumabbr[-1+110]+ ninjanumabbr[-1+125]; 
    ninjanumabbr[-1+125]= ninjanumabbr[-1+26]* ninjanumabbr[-1+125]; 
    ninjanumabbr[-1+127]= ninjanumabbr[-1+28]* ninjanumabbr[-1+111]; 
    ninjanumabbr[-1+128]= ninjanumabbr[-1+9]* ninjanumabbr[-1+80]; 
    ninjanumabbr[-1+129]= ninjanumabbr[-1+109]* ninjanumabbr[-1+24]; 
    ninjanumabbr[-1+130]= ninjanumabbr[-1+2]* powi2(ninjanumabbr[-1+1]); 
    ninjanumabbr[-1+126]= ninjanumabbr[-1+41]* ninjanumabbr[-1+126]; 
  
    ninja_result = 
      ninjanumabbr[-1+115]+ ninjanumabbr[-1+116]+ ninjanumabbr[-1+117]+ 
      ninjanumabbr[-1+118]+ ninjanumabbr[-1+119]+ ninjanumabbr[-1+120]+ 
      ninjanumabbr[-1+121]+ ninjanumabbr[-1+122]+ ninjanumabbr[-1+123]+ 
      ninjanumabbr[-1+124]+ ninjanumabbr[-1+125]+ ninjanumabbr[-1+126]+ 
      ninjanumabbr[-1+127]+ ninjanumabbr[-1+128]+ ninjanumabbr[-1+129]+ 
      ninjanumabbr[-1+130]; 
  	return ninja_result;
  }

  void NINJA_NUM::muExpansion(const ninja::ComplexMomentum ninjaV[],
							  const ninja::PartitionInt ninja_cutidx[],
							  ninja::Complex ninjaC[])
  {
	ninja::ComplexMomentum ninjaA0 = ninjaV[0];
#if (NINJA_RANK_MINUS_N > 0)
	ninja::ComplexMomentum ninjaA1 = ninjaV[1];
	(void)(ninjaA1);
#endif
	(void)(ninjaA0);
	(void)(ninja_cutidx);
	(void)(ninjaC);
  }

  void NINJA_NUM::t3Expansion(const ninja::ComplexMomentum & ninjaA,
							  const ninja::ComplexMomentum & ninjaE3,
							  const ninja::ComplexMomentum & ninjaE4,
							  const ninja::Complex & ninjaP,
							  int ninja_mindeg, int ninja_cut,
							  const ninja::PartitionInt ninja_cutidx[],
							  ninja::Complex ninjaC[])
  {
    const int ninjaidxt2mu0 = 0;
    const int ninjaidxt1mu0 = 1;
    const int ninjaidxt0mu0 = 2;
    const int ninjaidxt0mu2 = 3;
	(void)(ninjaA);
	(void)(ninjaE3);
	(void)(ninjaE4);
	(void)(ninjaP);
	(void)(ninja_mindeg);
	(void)(ninja_cut);
	(void)(ninja_cutidx);
	(void)(ninjaC);
	{
      NinjaAbbrType ninjanumabbr[1];  (void)(ninjanumabbr);
  
 
      ninjaC[0+ninjaidxt2mu0]= 
        NINJA_REAL(0); 
  	}
	if (ninja_mindeg > 1+NINJA_RANK_MINUS_N) {
      NinjaAbbrType ninjanumabbr[154];  (void)(ninjanumabbr);
  
      ninjanumabbr[-1+1]= ninjaMP ( ninjaA , ninjaE3 ) ; 
      ninjanumabbr[-1+2]= ninjaMP ( ninjaE3 , e1 ) ; 
      ninjanumabbr[-1+3]= ninjaMP ( ninjaE3 , e2 ) ; 
      ninjanumabbr[-1+4]= globabbr ( 53 ) ; 
      ninjanumabbr[-1+5]= ninjaMP ( ninjaE3 , spvae2k2 ) ; 
      ninjanumabbr[-1+6]= globabbr ( 32 ) ; 
      ninjanumabbr[-1+7]= ninjaMP ( ninjaE3 , spval5e2 ) ; 
      ninjanumabbr[-1+8]= globabbr ( 102 ) ; 
      ninjanumabbr[-1+9]= ninjaMP ( ninjaE3 , spvae1k2 ) ; 
      ninjanumabbr[-1+10]= globabbr ( 24 ) ; 
      ninjanumabbr[-1+11]= ninjaMP ( ninjaE3 , spval5e1 ) ; 
      ninjanumabbr[-1+12]= globabbr ( 12 ) ; 
      ninjanumabbr[-1+13]= ninjaMP ( ninjaE3 , k1 ) ; 
      ninjanumabbr[-1+14]= globabbr ( 123 ) ; 
      ninjanumabbr[-1+15]= globabbr ( 19 ) ; 
      ninjanumabbr[-1+16]= globabbr ( 97 ) ; 
      ninjanumabbr[-1+17]= globabbr ( 54 ) ; 
      ninjanumabbr[-1+18]= globabbr ( 126 ) ; 
      ninjanumabbr[-1+19]= ninjaMP ( ninjaE3 , k2 ) ; 
      ninjanumabbr[-1+20]= globabbr ( 52 ) ; 
      ninjanumabbr[-1+21]= globabbr ( 86 ) ; 
      ninjanumabbr[-1+22]= globabbr ( 45 ) ; 
      ninjanumabbr[-1+23]= globabbr ( 63 ) ; 
      ninjanumabbr[-1+24]= globabbr ( 84 ) ; 
      ninjanumabbr[-1+25]= ninjaMP ( ninjaE3 , l4 ) ; 
      ninjanumabbr[-1+26]= globabbr ( 146 ) ; 
      ninjanumabbr[-1+27]= globabbr ( 143 ) ; 
      ninjanumabbr[-1+28]= globabbr ( 104 ) ; 
      ninjanumabbr[-1+29]= globabbr ( 58 ) ; 
      ninjanumabbr[-1+30]= globabbr ( 87 ) ; 
      ninjanumabbr[-1+31]= ninjaMP ( ninjaE3 , l5 ) ; 
      ninjanumabbr[-1+32]= globabbr ( 131 ) ; 
      ninjanumabbr[-1+33]= ninjaMP ( ninjaE3 , spvak1k2 ) ; 
      ninjanumabbr[-1+34]= globabbr ( 31 ) ; 
      ninjanumabbr[-1+35]= ninjaMP ( ninjaE3 , spvak1l4 ) ; 
      ninjanumabbr[-1+36]= globabbr ( 76 ) ; 
      ninjanumabbr[-1+37]= ninjaMP ( ninjaE3 , spvak2k1 ) ; 
      ninjanumabbr[-1+38]= globabbr ( 66 ) ; 
      ninjanumabbr[-1+39]= ninjaMP ( ninjaE3 , spvak2l4 ) ; 
      ninjanumabbr[-1+40]= globabbr ( 71 ) ; 
      ninjanumabbr[-1+41]= ninjaMP ( ninjaE3 , spval5k1 ) ; 
      ninjanumabbr[-1+42]= globabbr ( 27 ) ; 
      ninjanumabbr[-1+43]= ninjaMP ( ninjaE3 , spval5k2 ) ; 
      ninjanumabbr[-1+44]= globabbr ( 38 ) ; 
      ninjanumabbr[-1+45]= ninjaMP ( ninjaE3 , spval5l4 ) ; 
      ninjanumabbr[-1+46]= globabbr ( 74 ) ; 
      ninjanumabbr[-1+47]= ninjaMP ( ninjaA , ninjaA ) ; 
      ninjanumabbr[-1+48]= globabbr ( 75 ) ; 
      ninjanumabbr[-1+49]= ninjaMP ( ninjaA , e1 ) ; 
      ninjanumabbr[-1+50]= ninjaMP ( ninjaA , e2 ) ; 
      ninjanumabbr[-1+51]= ninjaMP ( ninjaA , spvae1k2 ) ; 
      ninjanumabbr[-1+52]= ninjaMP ( ninjaA , spvae2k2 ) ; 
      ninjanumabbr[-1+53]= ninjaMP ( ninjaA , spval5e1 ) ; 
      ninjanumabbr[-1+54]= ninjaMP ( ninjaA , spval5e2 ) ; 
      ninjanumabbr[-1+55]= globabbr ( 59 ) ; 
      ninjanumabbr[-1+56]= globabbr ( 11 ) ; 
      ninjanumabbr[-1+57]= globabbr ( 62 ) ; 
      ninjanumabbr[-1+58]= globabbr ( 8 ) ; 
      ninjanumabbr[-1+59]= globabbr ( 36 ) ; 
      ninjanumabbr[-1+60]= globabbr ( 25 ) ; 
      ninjanumabbr[-1+61]= globabbr ( 41 ) ; 
      ninjanumabbr[-1+62]= globabbr ( 55 ) ; 
      ninjanumabbr[-1+63]= globabbr ( 51 ) ; 
      ninjanumabbr[-1+64]= globabbr ( 49 ) ; 
      ninjanumabbr[-1+65]= globabbr ( 20 ) ; 
      ninjanumabbr[-1+66]= globabbr ( 10 ) ; 
      ninjanumabbr[-1+67]= ninjaMP ( ninjaA , k1 ) ; 
      ninjanumabbr[-1+68]= ninjaMP ( ninjaA , k2 ) ; 
      ninjanumabbr[-1+69]= ninjaMP ( ninjaA , l4 ) ; 
      ninjanumabbr[-1+70]= ninjaMP ( ninjaA , l5 ) ; 
      ninjanumabbr[-1+71]= ninjaMP ( ninjaA , spvak1k2 ) ; 
      ninjanumabbr[-1+72]= ninjaMP ( ninjaA , spvak1l4 ) ; 
      ninjanumabbr[-1+73]= ninjaMP ( ninjaA , spvak2k1 ) ; 
      ninjanumabbr[-1+74]= ninjaMP ( ninjaA , spvak2l4 ) ; 
      ninjanumabbr[-1+75]= ninjaMP ( ninjaA , spval5k1 ) ; 
      ninjanumabbr[-1+76]= ninjaMP ( ninjaA , spval5k2 ) ; 
      ninjanumabbr[-1+77]= ninjaMP ( ninjaA , spval5l4 ) ; 
      ninjanumabbr[-1+78]= globabbr ( 133 ) ; 
      ninjanumabbr[-1+79]= globabbr ( 72 ) ; 
      ninjanumabbr[-1+80]= globabbr ( 140 ) ; 
      ninjanumabbr[-1+81]= globabbr ( 115 ) ; 
      ninjanumabbr[-1+82]= globabbr ( 40 ) ; 
      ninjanumabbr[-1+83]= globabbr ( 77 ) ; 
      ninjanumabbr[-1+84]= globabbr ( 88 ) ; 
      ninjanumabbr[-1+85]= globabbr ( 81 ) ; 
      ninjanumabbr[-1+86]= globabbr ( 6 ) ; 
      ninjanumabbr[-1+87]= globabbr ( 137 ) ; 
      ninjanumabbr[-1+88]= globabbr ( 96 ) ; 
      ninjanumabbr[-1+89]= globabbr ( 50 ) ; 
      ninjanumabbr[-1+90]= globabbr ( 39 ) ; 
      ninjanumabbr[-1+91]= globabbr ( 56 ) ; 
      ninjanumabbr[-1+92]= globabbr ( 37 ) ; 
      ninjanumabbr[-1+93]= globabbr ( 153 ) ; 
      ninjanumabbr[-1+94]= globabbr ( 47 ) ; 
      ninjanumabbr[-1+95]= globabbr ( 132 ) ; 
      ninjanumabbr[-1+96]= globabbr ( 26 ) ; 
      ninjanumabbr[-1+97]= globabbr ( 100 ) ; 
      ninjanumabbr[-1+98]= globabbr ( 42 ) ; 
      ninjanumabbr[-1+99]= globabbr ( 35 ) ; 
      ninjanumabbr[-1+100]= globabbr ( 34 ) ; 
      ninjanumabbr[-1+101]= globabbr ( 7 ) ; 
      ninjanumabbr[-1+102]= globabbr ( 129 ) ; 
      ninjanumabbr[-1+103]= globabbr ( 79 ) ; 
      ninjanumabbr[-1+104]= globabbr ( 48 ) ; 
      ninjanumabbr[-1+105]= globabbr ( 29 ) ; 
      ninjanumabbr[-1+106]= ninjaMP ( ninjaE3 , spval4k2 ) ; 
      ninjanumabbr[-1+107]= globabbr ( 18 ) ; 
      ninjanumabbr[-1+108]= globabbr ( 23 ) ; 
      ninjanumabbr[-1+109]= globabbr ( 9 ) ; 
      ninjanumabbr[-1+110]= globabbr ( 68 ) ; 
      ninjanumabbr[-1+111]= globabbr ( 33 ) ; 
      ninjanumabbr[-1+112]= globabbr ( 46 ) ; 
      ninjanumabbr[-1+113]= globabbr ( 14 ) ; 
      ninjanumabbr[-1+114]= globabbr ( 65 ) ; 
      ninjanumabbr[-1+115]= globabbr ( 28 ) ; 
      ninjanumabbr[-1+116]= globabbr ( 60 ) ; 
      ninjanumabbr[-1+117]= globabbr ( 67 ) ; 
      ninjanumabbr[-1+118]= globabbr ( 43 ) ; 
      ninjanumabbr[-1+119]= globabbr ( 73 ) ; 
      ninjanumabbr[-1+120]= ninjanumabbr[-1+43]* ninjanumabbr[-1+44]; 
      ninjanumabbr[-1+121]= ninjanumabbr[-1+32]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+122]= ninjanumabbr[-1+19]* ninjanumabbr[-1+20]; 
      ninjanumabbr[-1+123]= ninjanumabbr[-1+34]* ninjanumabbr[-1+33]; 
      ninjanumabbr[-1+124]= ninjanumabbr[-1+37]* ninjanumabbr[-1+38]; 
      ninjanumabbr[-1+125]= NINJA_REAL(2)* ninjanumabbr[-1+1]; 
      ninjanumabbr[-1+126]= ninjanumabbr[-1+125]* ninjanumabbr[-1+4]; 
      ninjanumabbr[-1+127]= ninjanumabbr[-1+35]* ninjanumabbr[-1+36]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+14]* ninjanumabbr[-1+13]; 
      ninjanumabbr[-1+120]= ninjanumabbr[-1+127]+ ninjanumabbr[-1+128]+ 
        ninjanumabbr[-1+126]+ ninjanumabbr[-1+124]+ ninjanumabbr[-1+121]+ 
        ninjanumabbr[-1+120]+ ninjanumabbr[-1+122]+ ninjanumabbr[-1+123]; 
      ninjanumabbr[-1+121]= ninjanumabbr[-1+40]* ninjanumabbr[-1+39]; 
      ninjanumabbr[-1+122]= ninjanumabbr[-1+41]* ninjanumabbr[-1+42]; 
      ninjanumabbr[-1+121]= ninjanumabbr[-1+120]+ ninjanumabbr[-1+121]+ 
        ninjanumabbr[-1+122]; 
      ninjanumabbr[-1+122]= ninjanumabbr[-1+3]* ninjanumabbr[-1+121]; 
      ninjanumabbr[-1+123]= ninjanumabbr[-1+13]- ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+124]= - ninjanumabbr[-1+16]* ninjanumabbr[-1+123]; 
      ninjanumabbr[-1+126]= ninjanumabbr[-1+19]* ninjanumabbr[-1+22]; 
      ninjanumabbr[-1+127]= ninjanumabbr[-1+25]* ninjanumabbr[-1+28]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+125]* ninjanumabbr[-1+8]; 
      ninjanumabbr[-1+124]= - ninjanumabbr[-1+128]+ ninjanumabbr[-1+127]+ 
        ninjanumabbr[-1+126]+ ninjanumabbr[-1+124]; 
      ninjanumabbr[-1+126]= ninjanumabbr[-1+124]* ninjanumabbr[-1+7]; 
      ninjanumabbr[-1+127]= ninjanumabbr[-1+15]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+19]* ninjanumabbr[-1+21]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+25]* ninjanumabbr[-1+27]; 
      ninjanumabbr[-1+130]= ninjanumabbr[-1+125]* ninjanumabbr[-1+6]; 
      ninjanumabbr[-1+127]= ninjanumabbr[-1+129]+ ninjanumabbr[-1+128]+ 
        ninjanumabbr[-1+127]- ninjanumabbr[-1+130]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+127]* ninjanumabbr[-1+5]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+5]* ninjanumabbr[-1+15]; 
      ninjanumabbr[-1+130]= ninjanumabbr[-1+129]* ninjanumabbr[-1+13]; 
      ninjanumabbr[-1+126]= ninjanumabbr[-1+128]+ ninjanumabbr[-1+126]- 
        ninjanumabbr[-1+130]; 
      ninjanumabbr[-1+122]= ninjanumabbr[-1+122]+ ninjanumabbr[-1+126]; 
      ninjanumabbr[-1+122]= ninjanumabbr[-1+2]* ninjanumabbr[-1+122]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+19]* ninjanumabbr[-1+24]; 
      ninjanumabbr[-1+130]= ninjanumabbr[-1+30]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+128]+ ninjanumabbr[-1+130]; 
      ninjanumabbr[-1+130]= ninjanumabbr[-1+11]* ninjanumabbr[-1+128]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+11]* ninjanumabbr[-1+12]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+131]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+130]= ninjanumabbr[-1+132]+ ninjanumabbr[-1+130]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+17]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+133]= ninjanumabbr[-1+23]* ninjanumabbr[-1+19]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+125]* ninjanumabbr[-1+10]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+134]+ ninjanumabbr[-1+132]+ 
        ninjanumabbr[-1+133]; 
      ninjanumabbr[-1+133]= ninjanumabbr[-1+25]* ninjanumabbr[-1+29]; 
      ninjanumabbr[-1+133]= ninjanumabbr[-1+133]+ ninjanumabbr[-1+132]; 
      ninjanumabbr[-1+134]= - ninjanumabbr[-1+13]* ninjanumabbr[-1+17]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+134]+ ninjanumabbr[-1+133]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+9]* ninjanumabbr[-1+134]; 
      ninjanumabbr[-1+135]= ninjanumabbr[-1+11]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+136]= ninjanumabbr[-1+13]* ninjanumabbr[-1+11]; 
      ninjanumabbr[-1+135]= ninjanumabbr[-1+135]- ninjanumabbr[-1+136]; 
      ninjanumabbr[-1+137]= ninjanumabbr[-1+18]* ninjanumabbr[-1+135]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+137]+ ninjanumabbr[-1+134]+ 
        ninjanumabbr[-1+130]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+3]* ninjanumabbr[-1+134]; 
      ninjanumabbr[-1+137]= ninjanumabbr[-1+26]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+138]= ninjanumabbr[-1+46]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+137]= ninjanumabbr[-1+137]+ ninjanumabbr[-1+138]; 
      ninjanumabbr[-1+138]= ninjanumabbr[-1+2]* ninjanumabbr[-1+3]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+138]* ninjanumabbr[-1+137]; 
      ninjanumabbr[-1+122]= ninjanumabbr[-1+122]+ ninjanumabbr[-1+139]+ 
        ninjanumabbr[-1+134]; 
      ninjanumabbr[-1+134]= - ninjanumabbr[-1+5]* ninjanumabbr[-1+6]; 
      ninjanumabbr[-1+139]= - ninjanumabbr[-1+7]* ninjanumabbr[-1+8]; 
      ninjanumabbr[-1+140]= ninjanumabbr[-1+3]* ninjanumabbr[-1+4]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+140]+ ninjanumabbr[-1+134]+ 
        ninjanumabbr[-1+139]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+2]* ninjanumabbr[-1+134]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+9]* ninjanumabbr[-1+10]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+131]+ ninjanumabbr[-1+139]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+3]* ninjanumabbr[-1+139]; 
      ninjanumabbr[-1+134]= ninjanumabbr[-1+139]+ ninjanumabbr[-1+134]; 
      ninjanumabbr[-1+120]= ninjanumabbr[-1+50]* ninjanumabbr[-1+120]; 
      ninjanumabbr[-1+139]= ninjaP + ninjanumabbr[-1+47]; 
      ninjanumabbr[-1+140]= ninjanumabbr[-1+4]* ninjanumabbr[-1+139]; 
      ninjanumabbr[-1+141]= ninjanumabbr[-1+44]* ninjanumabbr[-1+76]; 
      ninjanumabbr[-1+142]= ninjanumabbr[-1+38]* ninjanumabbr[-1+73]; 
      ninjanumabbr[-1+143]= ninjanumabbr[-1+20]* ninjanumabbr[-1+68]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+32]* ninjanumabbr[-1+70]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+34]* ninjanumabbr[-1+71]; 
      ninjanumabbr[-1+146]= ninjanumabbr[-1+75]* ninjanumabbr[-1+42]; 
      ninjanumabbr[-1+147]= ninjanumabbr[-1+14]* ninjanumabbr[-1+67]; 
      ninjanumabbr[-1+140]= ninjanumabbr[-1+147]+ ninjanumabbr[-1+146]+ 
        ninjanumabbr[-1+145]+ ninjanumabbr[-1+144]+ ninjanumabbr[-1+143]+ 
        ninjanumabbr[-1+142]+ ninjanumabbr[-1+104]+ ninjanumabbr[-1+141]+ 
        ninjanumabbr[-1+140]; 
      ninjanumabbr[-1+140]= ninjanumabbr[-1+3]* ninjanumabbr[-1+140]; 
      ninjanumabbr[-1+124]= ninjanumabbr[-1+54]* ninjanumabbr[-1+124]; 
      ninjanumabbr[-1+141]= ninjanumabbr[-1+67]- ninjanumabbr[-1+70]; 
      ninjanumabbr[-1+142]= - ninjanumabbr[-1+16]* ninjanumabbr[-1+141]; 
      ninjanumabbr[-1+143]= - ninjanumabbr[-1+8]* ninjanumabbr[-1+139]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+28]* ninjanumabbr[-1+69]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+22]* ninjanumabbr[-1+68]; 
      ninjanumabbr[-1+142]= ninjanumabbr[-1+145]+ ninjanumabbr[-1+112]+ 
        ninjanumabbr[-1+144]+ ninjanumabbr[-1+143]+ ninjanumabbr[-1+142]; 
      ninjanumabbr[-1+142]= ninjanumabbr[-1+7]* ninjanumabbr[-1+142]; 
      ninjanumabbr[-1+143]= ninjanumabbr[-1+13]* ninjanumabbr[-1+15]; 
      ninjanumabbr[-1+127]= - ninjanumabbr[-1+143]+ ninjanumabbr[-1+127]; 
      ninjanumabbr[-1+127]= ninjanumabbr[-1+52]* ninjanumabbr[-1+127]; 
      ninjanumabbr[-1+143]= - ninjanumabbr[-1+6]* ninjanumabbr[-1+139]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+27]* ninjanumabbr[-1+69]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+21]* ninjanumabbr[-1+68]; 
      ninjanumabbr[-1+143]= ninjanumabbr[-1+145]+ ninjanumabbr[-1+144]+ 
        ninjanumabbr[-1+111]+ ninjanumabbr[-1+143]; 
      ninjanumabbr[-1+143]= ninjanumabbr[-1+5]* ninjanumabbr[-1+143]; 
      ninjanumabbr[-1+129]= - ninjanumabbr[-1+129]* ninjanumabbr[-1+141]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+50]* ninjanumabbr[-1+39]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+3]* ninjanumabbr[-1+74]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+144]+ ninjanumabbr[-1+145]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+40]* ninjanumabbr[-1+144]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+50]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+146]= ninjanumabbr[-1+3]* ninjanumabbr[-1+69]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+145]+ ninjanumabbr[-1+146]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+26]* ninjanumabbr[-1+145]; 
      ninjanumabbr[-1+146]= ninjanumabbr[-1+105]* ninjanumabbr[-1+33]; 
      ninjanumabbr[-1+147]= ninjanumabbr[-1+110]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+148]= ninjanumabbr[-1+43]* ninjanumabbr[-1+109]; 
      ninjanumabbr[-1+149]= ninjanumabbr[-1+106]* ninjanumabbr[-1+107]; 
      ninjanumabbr[-1+150]= ninjanumabbr[-1+25]* ninjanumabbr[-1+96]; 
      ninjanumabbr[-1+151]= ninjanumabbr[-1+59]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+152]= ninjanumabbr[-1+50]* ninjanumabbr[-1+42]; 
      ninjanumabbr[-1+152]= ninjanumabbr[-1+108]+ ninjanumabbr[-1+152]; 
      ninjanumabbr[-1+152]= ninjanumabbr[-1+41]* ninjanumabbr[-1+152]; 
      ninjanumabbr[-1+153]= ninjanumabbr[-1+81]* ninjanumabbr[-1+13]; 
      ninjanumabbr[-1+154]= ninjanumabbr[-1+102]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+120]= ninjanumabbr[-1+127]+ ninjanumabbr[-1+154]+ 
        ninjanumabbr[-1+145]+ ninjanumabbr[-1+153]+ ninjanumabbr[-1+152]+ 
        ninjanumabbr[-1+144]+ ninjanumabbr[-1+140]+ ninjanumabbr[-1+142]+ 
        ninjanumabbr[-1+151]+ ninjanumabbr[-1+124]+ ninjanumabbr[-1+150]+ 
        ninjanumabbr[-1+149]+ ninjanumabbr[-1+148]+ ninjanumabbr[-1+147]+ 
        ninjanumabbr[-1+146]+ ninjanumabbr[-1+143]+ ninjanumabbr[-1+120]+ 
        ninjanumabbr[-1+129]; 
      ninjanumabbr[-1+120]= ninjanumabbr[-1+2]* ninjanumabbr[-1+120]; 
      ninjanumabbr[-1+124]= ninjanumabbr[-1+10]* ninjanumabbr[-1+139]; 
      ninjanumabbr[-1+127]= - ninjanumabbr[-1+17]* ninjanumabbr[-1+141]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+23]* ninjanumabbr[-1+68]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+29]* ninjanumabbr[-1+69]; 
      ninjanumabbr[-1+124]= ninjanumabbr[-1+118]+ ninjanumabbr[-1+139]+ 
        ninjanumabbr[-1+129]+ ninjanumabbr[-1+127]+ ninjanumabbr[-1+124]; 
      ninjanumabbr[-1+124]= ninjanumabbr[-1+9]* ninjanumabbr[-1+124]; 
      ninjanumabbr[-1+127]= ninjanumabbr[-1+51]* ninjanumabbr[-1+132]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+47]* ninjanumabbr[-1+12]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+24]* ninjanumabbr[-1+68]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+30]* ninjanumabbr[-1+69]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+139]+ ninjanumabbr[-1+132]+ 
        ninjanumabbr[-1+129]+ ninjanumabbr[-1+119]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+11]* ninjanumabbr[-1+129]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+12]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+139]= - ninjanumabbr[-1+18]* ninjanumabbr[-1+123]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+139]+ ninjanumabbr[-1+132]+ 
        ninjanumabbr[-1+128]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+53]* ninjanumabbr[-1+128]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+117]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+43]* ninjanumabbr[-1+116]; 
      ninjanumabbr[-1+131]= ninjaP * ninjanumabbr[-1+131]; 
      ninjanumabbr[-1+140]= ninjanumabbr[-1+106]* ninjanumabbr[-1+114]; 
      ninjanumabbr[-1+142]= ninjanumabbr[-1+103]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+143]= ninjanumabbr[-1+60]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+29]* ninjanumabbr[-1+51]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+97]+ ninjanumabbr[-1+144]; 
      ninjanumabbr[-1+144]= ninjanumabbr[-1+25]* ninjanumabbr[-1+144]; 
      ninjanumabbr[-1+145]= ninjanumabbr[-1+90]* ninjanumabbr[-1+19]; 
      ninjanumabbr[-1+146]= - ninjanumabbr[-1+17]* ninjanumabbr[-1+51]; 
      ninjanumabbr[-1+146]= ninjanumabbr[-1+82]+ ninjanumabbr[-1+146]; 
      ninjanumabbr[-1+146]= ninjanumabbr[-1+13]* ninjanumabbr[-1+146]; 
      ninjanumabbr[-1+147]= ninjanumabbr[-1+113]* ninjanumabbr[-1+33]; 
      ninjanumabbr[-1+124]= ninjanumabbr[-1+128]+ ninjanumabbr[-1+147]+ 
        ninjanumabbr[-1+146]+ ninjanumabbr[-1+145]+ ninjanumabbr[-1+144]+ 
        ninjanumabbr[-1+143]+ ninjanumabbr[-1+142]+ ninjanumabbr[-1+140]+ 
        ninjanumabbr[-1+131]+ ninjanumabbr[-1+139]+ ninjanumabbr[-1+132]+ 
        ninjanumabbr[-1+129]+ ninjanumabbr[-1+127]+ ninjanumabbr[-1+124]; 
      ninjanumabbr[-1+124]= ninjanumabbr[-1+3]* ninjanumabbr[-1+124]; 
      ninjanumabbr[-1+121]= ninjanumabbr[-1+137]+ ninjanumabbr[-1+121]; 
      ninjanumabbr[-1+121]= ninjanumabbr[-1+3]* ninjanumabbr[-1+121]; 
      ninjanumabbr[-1+121]= ninjanumabbr[-1+121]+ ninjanumabbr[-1+126]; 
      ninjanumabbr[-1+121]= ninjanumabbr[-1+49]* ninjanumabbr[-1+121]; 
      ninjanumabbr[-1+126]= ninjanumabbr[-1+88]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+127]= - ninjanumabbr[-1+93]* ninjanumabbr[-1+43]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+87]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+91]* ninjanumabbr[-1+33]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+56]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+94]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+137]= ninjanumabbr[-1+89]* ninjanumabbr[-1+2]; 
      ninjanumabbr[-1+126]= ninjanumabbr[-1+137]+ ninjanumabbr[-1+132]+ 
        ninjanumabbr[-1+131]+ ninjanumabbr[-1+129]+ ninjanumabbr[-1+128]+ 
        ninjanumabbr[-1+127]+ ninjanumabbr[-1+126]; 
      ninjanumabbr[-1+126]= ninjanumabbr[-1+19]* ninjanumabbr[-1+126]; 
      ninjanumabbr[-1+127]= ninjanumabbr[-1+83]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+55]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+19]* ninjanumabbr[-1+79]; 
      ninjanumabbr[-1+131]= - ninjanumabbr[-1+25]* ninjanumabbr[-1+80]; 
      ninjanumabbr[-1+132]= - ninjanumabbr[-1+50]* ninjanumabbr[-1+9]* 
        ninjanumabbr[-1+17]; 
      ninjanumabbr[-1+123]= - ninjanumabbr[-1+78]* ninjanumabbr[-1+123]; 
      ninjanumabbr[-1+123]= ninjanumabbr[-1+123]+ ninjanumabbr[-1+132]+ 
        ninjanumabbr[-1+131]+ ninjanumabbr[-1+129]+ ninjanumabbr[-1+127]+ 
        ninjanumabbr[-1+128]; 
      ninjanumabbr[-1+123]= ninjanumabbr[-1+13]* ninjanumabbr[-1+123]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+45]* ninjanumabbr[-1+101]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+98]* ninjanumabbr[-1+33]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+43]* ninjanumabbr[-1+100]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+57]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+137]= - ninjanumabbr[-1+95]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+99]* ninjanumabbr[-1+41]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+139]+ ninjanumabbr[-1+137]+ 
        ninjanumabbr[-1+132]+ ninjanumabbr[-1+131]+ ninjanumabbr[-1+128]+ 
        ninjanumabbr[-1+129]; 
      ninjanumabbr[-1+128]= ninjanumabbr[-1+25]* ninjanumabbr[-1+128]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+11]* ninjanumabbr[-1+66]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+58]* ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+65]* ninjanumabbr[-1+9]; 
      ninjanumabbr[-1+137]= ninjanumabbr[-1+63]* ninjanumabbr[-1+43]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+137]+ ninjanumabbr[-1+132]+ 
        ninjanumabbr[-1+131]+ ninjanumabbr[-1+129]; 
      ninjanumabbr[-1+129]= ninjanumabbr[-1+125]* ninjanumabbr[-1+129]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+9]* ninjanumabbr[-1+133]; 
      ninjanumabbr[-1+130]= ninjanumabbr[-1+131]+ ninjanumabbr[-1+130]; 
      ninjanumabbr[-1+130]= ninjanumabbr[-1+50]* ninjanumabbr[-1+130]; 
      ninjanumabbr[-1+125]= ninjanumabbr[-1+62]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+92]* ninjanumabbr[-1+19]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+3]* ninjanumabbr[-1+115]; 
      ninjanumabbr[-1+125]= ninjanumabbr[-1+132]+ ninjanumabbr[-1+125]+ 
        ninjanumabbr[-1+131]; 
      ninjanumabbr[-1+125]= ninjanumabbr[-1+41]* ninjanumabbr[-1+125]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+61]* ninjanumabbr[-1+33]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+64]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+131]+ ninjanumabbr[-1+132]; 
      ninjanumabbr[-1+131]= ninjanumabbr[-1+1]* ninjanumabbr[-1+131]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+50]* ninjanumabbr[-1+135]; 
      ninjanumabbr[-1+133]= - ninjanumabbr[-1+3]* ninjanumabbr[-1+11]* 
        ninjanumabbr[-1+141]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+133]+ ninjanumabbr[-1+132]; 
      ninjanumabbr[-1+132]= ninjanumabbr[-1+18]* ninjanumabbr[-1+132]; 
      ninjanumabbr[-1+133]= ninjanumabbr[-1+19]* ninjanumabbr[-1+11]; 
      ninjanumabbr[-1+133]= - ninjanumabbr[-1+133]+ ninjanumabbr[-1+136]; 
      ninjanumabbr[-1+133]= ninjanumabbr[-1+85]* ninjanumabbr[-1+133]; 
      ninjanumabbr[-1+135]= ninjanumabbr[-1+2]* ninjanumabbr[-1+50]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+136]= ninjanumabbr[-1+77]* ninjanumabbr[-1+138]; 
      ninjanumabbr[-1+135]= ninjanumabbr[-1+135]+ ninjanumabbr[-1+136]; 
      ninjanumabbr[-1+135]= ninjanumabbr[-1+46]* ninjanumabbr[-1+135]; 
      ninjanumabbr[-1+127]= - ninjanumabbr[-1+31]* ninjanumabbr[-1+127]; 
      ninjanumabbr[-1+136]= ninjanumabbr[-1+19]- ninjanumabbr[-1+13]; 
      ninjanumabbr[-1+136]= ninjanumabbr[-1+84]* ninjanumabbr[-1+9]* ninjanumabbr[-1+136]
        ; 
      ninjanumabbr[-1+137]= ninjanumabbr[-1+86]* powi2(ninjanumabbr[-1+19]); 
      ninjanumabbr[-1+139]= ninjanumabbr[-1+48]* powi2(ninjanumabbr[-1+1]); 
      ninjanumabbr[-1+138]= ninjanumabbr[-1+72]* ninjanumabbr[-1+36]* 
        ninjanumabbr[-1+138]; 
      ninjanumabbr[-1+120]= ninjanumabbr[-1+121]+ ninjanumabbr[-1+135]+ 
        ninjanumabbr[-1+138]+ NINJA_REAL(4)* ninjanumabbr[-1+139]+ ninjanumabbr[-1+133]+ 
        ninjanumabbr[-1+125]+ ninjanumabbr[-1+132]+ ninjanumabbr[-1+137]+ 
        ninjanumabbr[-1+136]+ ninjanumabbr[-1+130]+ NINJA_REAL(2)* ninjanumabbr[-1+131]+ 
        ninjanumabbr[-1+127]+ ninjanumabbr[-1+126]+ ninjanumabbr[-1+129]+ 
        ninjanumabbr[-1+120]+ ninjanumabbr[-1+128]+ ninjanumabbr[-1+123]+ 
        ninjanumabbr[-1+124]; 
  
      ninjaC[0+ninjaidxt1mu0]= 
        ninjanumabbr[-1+122]; 
  
      ninjaC[0+ninjaidxt0mu0]= 
        ninjanumabbr[-1+120]; 
  
      ninjaC[0+ninjaidxt0mu2]= 
        ninjanumabbr[-1+134]; 
  	}
  }

  void NINJA_NUM::t2Expansion(const ninja::ComplexMomentum & ninjaA0,
							  const ninja::ComplexMomentum & ninjaA1,
							  const ninja::ComplexMomentum & ninjaE3,
							  const ninja::ComplexMomentum & ninjaE4,
							  const ninja::Complex ninjaP[],
							  int ninja_mindeg, int ninja_cut,
							  const ninja::PartitionInt ninja_cutidx[],
							  ninja::Complex ninjaC[])
  {
    const int ninjaidxt1x0mu0 = 0;
    const int ninjaidxt0x0mu0 = 1;
    const int ninjaidxt0x1mu0 = 2;
	const ninja::Complex ninjaP0 = ninjaP[0];
	const ninja::Complex ninjaP1 = ninjaP[1];
	const ninja::Complex ninjaP2 = ninjaP[2];
	(void)(ninjaA0);
	(void)(ninjaA1);
	(void)(ninjaE3);
	(void)(ninjaE4);
	(void)(ninjaP0);
	(void)(ninjaP1);
	(void)(ninjaP2);
	(void)(ninja_mindeg);
	(void)(ninja_cut);
	(void)(ninja_cutidx);
	(void)(ninjaC);
	{
      NinjaAbbrType ninjanumabbr[1];  (void)(ninjanumabbr);
  
 
      ninjaC[0+ninjaidxt1x0mu0]= 
        NINJA_REAL(0); 
  	}
	if (ninja_mindeg > 1+NINJA_RANK_MINUS_N) {
      NinjaAbbrType ninjanumabbr[59];  (void)(ninjanumabbr);
  
      ninjanumabbr[-1+1]= ninjaMP ( ninjaA0 , ninjaE3 ) ; 
      ninjanumabbr[-1+2]= ninjaMP ( ninjaE3 , e1 ) ; 
      ninjanumabbr[-1+3]= ninjaMP ( ninjaE3 , e2 ) ; 
      ninjanumabbr[-1+4]= globabbr ( 53 ) ; 
      ninjanumabbr[-1+5]= ninjaMP ( ninjaE3 , spvae2k2 ) ; 
      ninjanumabbr[-1+6]= globabbr ( 32 ) ; 
      ninjanumabbr[-1+7]= ninjaMP ( ninjaE3 , spval5e2 ) ; 
      ninjanumabbr[-1+8]= globabbr ( 102 ) ; 
      ninjanumabbr[-1+9]= ninjaMP ( ninjaE3 , spvae1k2 ) ; 
      ninjanumabbr[-1+10]= globabbr ( 24 ) ; 
      ninjanumabbr[-1+11]= ninjaMP ( ninjaE3 , spval5e1 ) ; 
      ninjanumabbr[-1+12]= globabbr ( 12 ) ; 
      ninjanumabbr[-1+13]= ninjaMP ( ninjaE3 , k1 ) ; 
      ninjanumabbr[-1+14]= globabbr ( 123 ) ; 
      ninjanumabbr[-1+15]= globabbr ( 19 ) ; 
      ninjanumabbr[-1+16]= globabbr ( 97 ) ; 
      ninjanumabbr[-1+17]= globabbr ( 54 ) ; 
      ninjanumabbr[-1+18]= globabbr ( 126 ) ; 
      ninjanumabbr[-1+19]= ninjaMP ( ninjaE3 , k2 ) ; 
      ninjanumabbr[-1+20]= globabbr ( 52 ) ; 
      ninjanumabbr[-1+21]= globabbr ( 86 ) ; 
      ninjanumabbr[-1+22]= globabbr ( 45 ) ; 
      ninjanumabbr[-1+23]= globabbr ( 63 ) ; 
      ninjanumabbr[-1+24]= globabbr ( 84 ) ; 
      ninjanumabbr[-1+25]= ninjaMP ( ninjaE3 , l4 ) ; 
      ninjanumabbr[-1+26]= globabbr ( 146 ) ; 
      ninjanumabbr[-1+27]= globabbr ( 143 ) ; 
      ninjanumabbr[-1+28]= globabbr ( 104 ) ; 
      ninjanumabbr[-1+29]= globabbr ( 58 ) ; 
      ninjanumabbr[-1+30]= globabbr ( 87 ) ; 
      ninjanumabbr[-1+31]= ninjaMP ( ninjaE3 , l5 ) ; 
      ninjanumabbr[-1+32]= globabbr ( 131 ) ; 
      ninjanumabbr[-1+33]= ninjaMP ( ninjaE3 , spvak1k2 ) ; 
      ninjanumabbr[-1+34]= globabbr ( 31 ) ; 
      ninjanumabbr[-1+35]= ninjaMP ( ninjaE3 , spvak1l4 ) ; 
      ninjanumabbr[-1+36]= globabbr ( 76 ) ; 
      ninjanumabbr[-1+37]= ninjaMP ( ninjaE3 , spvak2k1 ) ; 
      ninjanumabbr[-1+38]= globabbr ( 66 ) ; 
      ninjanumabbr[-1+39]= ninjaMP ( ninjaE3 , spvak2l4 ) ; 
      ninjanumabbr[-1+40]= globabbr ( 71 ) ; 
      ninjanumabbr[-1+41]= ninjaMP ( ninjaE3 , spval5k1 ) ; 
      ninjanumabbr[-1+42]= globabbr ( 27 ) ; 
      ninjanumabbr[-1+43]= ninjaMP ( ninjaE3 , spval5k2 ) ; 
      ninjanumabbr[-1+44]= globabbr ( 38 ) ; 
      ninjanumabbr[-1+45]= ninjaMP ( ninjaE3 , spval5l4 ) ; 
      ninjanumabbr[-1+46]= globabbr ( 74 ) ; 
      ninjanumabbr[-1+47]= ninjanumabbr[-1+31]* ninjanumabbr[-1+32]; 
      ninjanumabbr[-1+48]= ninjanumabbr[-1+19]* ninjanumabbr[-1+20]; 
      ninjanumabbr[-1+49]= ninjanumabbr[-1+34]* ninjanumabbr[-1+33]; 
      ninjanumabbr[-1+50]= ninjanumabbr[-1+35]* ninjanumabbr[-1+36]; 
      ninjanumabbr[-1+51]= NINJA_REAL(2)* ninjanumabbr[-1+1]; 
      ninjanumabbr[-1+52]= ninjanumabbr[-1+4]* ninjanumabbr[-1+51]; 
      ninjanumabbr[-1+53]= ninjanumabbr[-1+46]* ninjanumabbr[-1+45]; 
      ninjanumabbr[-1+54]= ninjanumabbr[-1+13]* ninjanumabbr[-1+14]; 
      ninjanumabbr[-1+55]= ninjanumabbr[-1+42]* ninjanumabbr[-1+41]; 
      ninjanumabbr[-1+56]= ninjanumabbr[-1+43]* ninjanumabbr[-1+44]; 
      ninjanumabbr[-1+57]= ninjanumabbr[-1+39]* ninjanumabbr[-1+40]; 
      ninjanumabbr[-1+58]= ninjanumabbr[-1+26]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+59]= ninjanumabbr[-1+37]* ninjanumabbr[-1+38]; 
      ninjanumabbr[-1+47]= ninjanumabbr[-1+59]+ ninjanumabbr[-1+58]+ 
        ninjanumabbr[-1+57]+ ninjanumabbr[-1+56]+ ninjanumabbr[-1+55]+ 
        ninjanumabbr[-1+54]+ ninjanumabbr[-1+53]+ ninjanumabbr[-1+52]+ 
        ninjanumabbr[-1+50]+ ninjanumabbr[-1+49]+ ninjanumabbr[-1+47]+ 
        ninjanumabbr[-1+48]; 
      ninjanumabbr[-1+47]= ninjanumabbr[-1+2]* ninjanumabbr[-1+47]; 
      ninjanumabbr[-1+48]= ninjanumabbr[-1+13]- ninjanumabbr[-1+31]; 
      ninjanumabbr[-1+49]= - ninjanumabbr[-1+48]* ninjanumabbr[-1+18]; 
      ninjanumabbr[-1+50]= ninjanumabbr[-1+24]* ninjanumabbr[-1+19]; 
      ninjanumabbr[-1+52]= ninjanumabbr[-1+12]* ninjanumabbr[-1+51]; 
      ninjanumabbr[-1+53]= ninjanumabbr[-1+30]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+49]= ninjanumabbr[-1+49]+ ninjanumabbr[-1+53]+ 
        ninjanumabbr[-1+52]+ ninjanumabbr[-1+50]; 
      ninjanumabbr[-1+49]= ninjanumabbr[-1+11]* ninjanumabbr[-1+49]; 
      ninjanumabbr[-1+50]= ninjanumabbr[-1+19]* ninjanumabbr[-1+23]; 
      ninjanumabbr[-1+52]= ninjanumabbr[-1+29]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+53]= ninjanumabbr[-1+10]* ninjanumabbr[-1+51]; 
      ninjanumabbr[-1+54]= - ninjanumabbr[-1+17]* ninjanumabbr[-1+48]; 
      ninjanumabbr[-1+50]= ninjanumabbr[-1+54]+ ninjanumabbr[-1+53]+ 
        ninjanumabbr[-1+50]+ ninjanumabbr[-1+52]; 
      ninjanumabbr[-1+50]= ninjanumabbr[-1+9]* ninjanumabbr[-1+50]; 
      ninjanumabbr[-1+47]= ninjanumabbr[-1+50]+ ninjanumabbr[-1+47]+ 
        ninjanumabbr[-1+49]; 
      ninjanumabbr[-1+47]= ninjanumabbr[-1+3]* ninjanumabbr[-1+47]; 
      ninjanumabbr[-1+49]= - ninjanumabbr[-1+48]* ninjanumabbr[-1+16]; 
      ninjanumabbr[-1+50]= ninjanumabbr[-1+22]* ninjanumabbr[-1+19]; 
      ninjanumabbr[-1+52]= ninjanumabbr[-1+28]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+53]= - ninjanumabbr[-1+8]* ninjanumabbr[-1+51]; 
      ninjanumabbr[-1+49]= ninjanumabbr[-1+49]+ ninjanumabbr[-1+53]+ 
        ninjanumabbr[-1+52]+ ninjanumabbr[-1+50]; 
      ninjanumabbr[-1+49]= ninjanumabbr[-1+7]* ninjanumabbr[-1+49]; 
      ninjanumabbr[-1+48]= - ninjanumabbr[-1+15]* ninjanumabbr[-1+48]; 
      ninjanumabbr[-1+50]= ninjanumabbr[-1+27]* ninjanumabbr[-1+25]; 
      ninjanumabbr[-1+52]= ninjanumabbr[-1+21]* ninjanumabbr[-1+19]; 
      ninjanumabbr[-1+51]= - ninjanumabbr[-1+6]* ninjanumabbr[-1+51]; 
      ninjanumabbr[-1+48]= ninjanumabbr[-1+51]+ ninjanumabbr[-1+52]+ 
        ninjanumabbr[-1+50]+ ninjanumabbr[-1+48]; 
      ninjanumabbr[-1+48]= ninjanumabbr[-1+5]* ninjanumabbr[-1+48]; 
      ninjanumabbr[-1+48]= ninjanumabbr[-1+48]+ ninjanumabbr[-1+49]; 
      ninjanumabbr[-1+48]= ninjanumabbr[-1+2]* ninjanumabbr[-1+48]; 
      ninjanumabbr[-1+47]= ninjanumabbr[-1+48]+ ninjanumabbr[-1+47]; 
  
      ninjaC[0+ninjaidxt0x0mu0]= 
        ninjanumabbr[-1+47]; 
  
      ninjaC[0+ninjaidxt0x1mu0]= 
        NINJA_REAL(0); 
  	}
  }

#if NINJA_NUM_NAMESPACE
} // namespace NINJA_NUM_NAMESPACE
#endif
