name: CI on Fedora 

on: [push, pull_request]

jobs:
  build:
    name: Compile Fortran on ${{ matrix.platform }} with ${{ matrix.build_system }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
            build_system: autotools
          - platform: linux/arm64
            runner: ubuntu-22.04-arm
            build_system: autotools
          - platform: macos/amd64
            runner: macos-13
            build_system: autotools
          - platform: macos/arm64
            runner: macos-14
            build_system: autotools
    runs-on: ${{ matrix.runner || 'ubuntu-22.04' }}
    container: ${{ startsWith(matrix.runner, 'ubuntu') && 'fedora:latest' || null }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies on Fedora
        if: startsWith(matrix.runner, 'ubuntu')
        run: |
          dnf install -y gcc-gfortran gcc-c++ autogen autoconf automake libtool
          dnf install -y libquadmath-devel || echo "OK"

      - name: Install dependencies on macOS
        if: startsWith(matrix.runner, 'macos')
        run: |
          brew update
          brew install gcc autoconf automake libtool
  
      - name: Compile and run
        run: |
           if [ "${{ matrix.build_system }}" = "autotools" ]; then
           autoreconf -i 
           ./configure  --prefix=$(pwd)/MINSTALL --with-avholo=no --enable-quadninja=no  --with-quadruple=no --disable-f90module --disable-gosam --disable-avholo_cache --with-looptools=no
           make -j
           make install
           fi
